ALTER TABLE spaces ADD COLUMN card_height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spaces ADD COLUMN text_font_size INTEGER NOT NULL DEFAULT 13;
ALTER TABLE spaces ADD COLUMN text_font TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE spaces ADD COLUMN text_bold BOOLEAN NOT NULL DEFAULT false;
