// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersAdmin = `-- name: CountUsersAdmin :one
SELECT COUNT(*)::int AS total
FROM users
WHERE is_admin = false
  AND (name ILIKE '%' || $1::text || '%' OR email ILIKE '%' || $1::text || '%' OR $1::text = '')
`

func (q *Queries) CountUsersAdmin(ctx context.Context, search string) (int32, error) {
	row := q.db.QueryRow(ctx, countUsersAdmin, search)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getPageViewsByDay = `-- name: GetPageViewsByDay :many
SELECT
  date_trunc('day', created_at)::date AS date,
  COUNT(*)::int AS views
FROM page_views
WHERE created_at > now() - $1::interval
GROUP BY date
ORDER BY date
`

type GetPageViewsByDayRow struct {
	Date  pgtype.Date `json:"date"`
	Views int32       `json:"views"`
}

func (q *Queries) GetPageViewsByDay(ctx context.Context, period pgtype.Interval) ([]GetPageViewsByDayRow, error) {
	rows, err := q.db.Query(ctx, getPageViewsByDay, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPageViewsByDayRow{}
	for rows.Next() {
		var i GetPageViewsByDayRow
		if err := rows.Scan(&i.Date, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeriodPageViews = `-- name: GetPeriodPageViews :one
SELECT COUNT(*)::int AS total FROM page_views WHERE created_at > now() - $1::interval
`

func (q *Queries) GetPeriodPageViews(ctx context.Context, period pgtype.Interval) (int32, error) {
	row := q.db.QueryRow(ctx, getPeriodPageViews, period)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getRecentSignups = `-- name: GetRecentSignups :many
SELECT id, clerk_id, email, name, created_at
FROM users
WHERE is_admin = false
  AND created_at > now() - interval '7 days'
ORDER BY created_at DESC
`

type GetRecentSignupsRow struct {
	ID        uuid.UUID `json:"id"`
	ClerkID   string    `json:"clerk_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetRecentSignups(ctx context.Context) ([]GetRecentSignupsRow, error) {
	rows, err := q.db.Query(ctx, getRecentSignups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentSignupsRow{}
	for rows.Next() {
		var i GetRecentSignupsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayPageViews = `-- name: GetTodayPageViews :one
SELECT COUNT(*)::int AS total FROM page_views WHERE created_at >= CURRENT_DATE
`

func (q *Queries) GetTodayPageViews(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getTodayPageViews)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getTopPages = `-- name: GetTopPages :many
SELECT path, COUNT(*)::int AS views
FROM page_views
WHERE created_at > now() - $1::interval
GROUP BY path
ORDER BY views DESC
LIMIT 10
`

type GetTopPagesRow struct {
	Path  string `json:"path"`
	Views int32  `json:"views"`
}

func (q *Queries) GetTopPages(ctx context.Context, period pgtype.Interval) ([]GetTopPagesRow, error) {
	rows, err := q.db.Query(ctx, getTopPages, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopPagesRow{}
	for rows.Next() {
		var i GetTopPagesRow
		if err := rows.Scan(&i.Path, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopReferrers = `-- name: GetTopReferrers :many
SELECT
  COALESCE(NULLIF(referrer, ''), '(direct)') AS referrer,
  COUNT(*)::int AS views
FROM page_views
WHERE created_at > now() - $1::interval
GROUP BY referrer
ORDER BY views DESC
LIMIT 10
`

type GetTopReferrersRow struct {
	Referrer interface{} `json:"referrer"`
	Views    int32       `json:"views"`
}

func (q *Queries) GetTopReferrers(ctx context.Context, period pgtype.Interval) ([]GetTopReferrersRow, error) {
	rows, err := q.db.Query(ctx, getTopReferrers, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopReferrersRow{}
	for rows.Next() {
		var i GetTopReferrersRow
		if err := rows.Scan(&i.Referrer, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopUTMSources = `-- name: GetTopUTMSources :many
SELECT
  utm_source,
  COUNT(*)::int AS views
FROM page_views
WHERE created_at > now() - $1::interval
  AND utm_source IS NOT NULL AND utm_source != ''
GROUP BY utm_source
ORDER BY views DESC
LIMIT 10
`

type GetTopUTMSourcesRow struct {
	UtmSource pgtype.Text `json:"utm_source"`
	Views     int32       `json:"views"`
}

func (q *Queries) GetTopUTMSources(ctx context.Context, period pgtype.Interval) ([]GetTopUTMSourcesRow, error) {
	rows, err := q.db.Query(ctx, getTopUTMSources, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopUTMSourcesRow{}
	for rows.Next() {
		var i GetTopUTMSourcesRow
		if err := rows.Scan(&i.UtmSource, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalPageViews = `-- name: GetTotalPageViews :one
SELECT COUNT(*)::int AS total FROM page_views
`

func (q *Queries) GetTotalPageViews(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getTotalPageViews)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getTotalProducts = `-- name: GetTotalProducts :one
SELECT COUNT(*)::int AS total
FROM products
WHERE user_id NOT IN (SELECT id FROM users WHERE is_admin = true)
`

func (q *Queries) GetTotalProducts(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getTotalProducts)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getTotalProofs = `-- name: GetTotalProofs :one
SELECT COUNT(*)::int AS total
FROM proofs
WHERE product_id IN (
  SELECT p.id FROM products p
  JOIN users u ON u.id = p.user_id
  WHERE u.is_admin = false
)
`

func (q *Queries) GetTotalProofs(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getTotalProofs)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getUTMCampaigns = `-- name: GetUTMCampaigns :many
SELECT
  COALESCE(NULLIF(utm_source, ''), '(none)') AS utm_source,
  COALESCE(NULLIF(utm_campaign, ''), '(none)') AS utm_campaign,
  COUNT(*)::int AS views
FROM page_views
WHERE created_at > now() - $1::interval
  AND (utm_source IS NOT NULL AND utm_source != '')
GROUP BY utm_source, utm_campaign
ORDER BY views DESC
LIMIT 20
`

type GetUTMCampaignsRow struct {
	UtmSource   interface{} `json:"utm_source"`
	UtmCampaign interface{} `json:"utm_campaign"`
	Views       int32       `json:"views"`
}

func (q *Queries) GetUTMCampaigns(ctx context.Context, period pgtype.Interval) ([]GetUTMCampaignsRow, error) {
	rows, err := q.db.Query(ctx, getUTMCampaigns, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUTMCampaignsRow{}
	for rows.Next() {
		var i GetUTMCampaignsRow
		if err := rows.Scan(&i.UtmSource, &i.UtmCampaign, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStats = `-- name: GetUserStats :one
SELECT
  COUNT(*)::int AS total_users,
  COUNT(*) FILTER (WHERE plan IN ('pro', 'business'))::int AS paid_users,
  COUNT(*) FILTER (WHERE plan = 'pro')::int AS pro_users,
  COUNT(*) FILTER (WHERE plan = 'business')::int AS business_users,
  COUNT(*) FILTER (WHERE created_at > now() - interval '7 days')::int AS signups_this_week,
  COUNT(*) FILTER (WHERE plan IN ('pro', 'business') AND created_at > now() - interval '7 days')::int AS paid_this_week
FROM users
WHERE is_admin = false
`

type GetUserStatsRow struct {
	TotalUsers      int32 `json:"total_users"`
	PaidUsers       int32 `json:"paid_users"`
	ProUsers        int32 `json:"pro_users"`
	BusinessUsers   int32 `json:"business_users"`
	SignupsThisWeek int32 `json:"signups_this_week"`
	PaidThisWeek    int32 `json:"paid_this_week"`
}

func (q *Queries) GetUserStats(ctx context.Context) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats)
	var i GetUserStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.PaidUsers,
		&i.ProUsers,
		&i.BusinessUsers,
		&i.SignupsThisWeek,
		&i.PaidThisWeek,
	)
	return i, err
}

const isUserAdmin = `-- name: IsUserAdmin :one
SELECT is_admin FROM users WHERE clerk_id = $1
`

func (q *Queries) IsUserAdmin(ctx context.Context, clerkID string) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAdmin, clerkID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT
  u.id, u.clerk_id, u.email, u.name, u.plan, u.is_admin, u.created_at,
  COUNT(DISTINCT p.id)::int AS product_count,
  COUNT(DISTINCT pr.id)::int AS proof_count
FROM users u
LEFT JOIN products p ON p.user_id = u.id
LEFT JOIN proofs pr ON pr.product_id = p.id
WHERE u.is_admin = false
  AND (u.name ILIKE '%' || $1::text || '%' OR u.email ILIKE '%' || $1::text || '%' OR $1::text = '')
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListUsersAdminParams struct {
	Search    string `json:"search"`
	OffsetVal int32  `json:"offset_val"`
	LimitVal  int32  `json:"limit_val"`
}

type ListUsersAdminRow struct {
	ID           uuid.UUID `json:"id"`
	ClerkID      string    `json:"clerk_id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Plan         UserPlan  `json:"plan"`
	IsAdmin      bool      `json:"is_admin"`
	CreatedAt    time.Time `json:"created_at"`
	ProductCount int32     `json:"product_count"`
	ProofCount   int32     `json:"proof_count"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Search, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersAdminRow{}
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ClerkID,
			&i.Email,
			&i.Name,
			&i.Plan,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ProductCount,
			&i.ProofCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPageView = `-- name: RecordPageView :exec
INSERT INTO page_views (path, referrer, user_agent, utm_source, utm_medium, utm_campaign)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordPageViewParams struct {
	Path        string      `json:"path"`
	Referrer    pgtype.Text `json:"referrer"`
	UserAgent   pgtype.Text `json:"user_agent"`
	UtmSource   pgtype.Text `json:"utm_source"`
	UtmMedium   pgtype.Text `json:"utm_medium"`
	UtmCampaign pgtype.Text `json:"utm_campaign"`
}

func (q *Queries) RecordPageView(ctx context.Context, arg RecordPageViewParams) error {
	_, err := q.db.Exec(ctx, recordPageView,
		arg.Path,
		arg.Referrer,
		arg.UserAgent,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
	)
	return err
}
