// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embeds.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmbedsByProductID = `-- name: CountEmbedsByProductID :one
SELECT COUNT(*) FROM embeds WHERE product_id = $1
`

func (q *Queries) CountEmbedsByProductID(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmbedsByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmbed = `-- name: CreateEmbed :one
INSERT INTO embeds (product_id, name, slug, layout)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, name, slug, layout, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, show_header, header_text_color, subtitle, max_items, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_opacity, rows, width_percent, auto_scroll, scroll_direction, created_at, updated_at
`

type CreateEmbedParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Layout    string    `json:"layout"`
}

func (q *Queries) CreateEmbed(ctx context.Context, arg CreateEmbedParams) (Embed, error) {
	row := q.db.QueryRow(ctx, createEmbed,
		arg.ProductID,
		arg.Name,
		arg.Slug,
		arg.Layout,
	)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Layout,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.ShowHeader,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.MaxItems,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgOpacity,
		&i.Rows,
		&i.WidthPercent,
		&i.AutoScroll,
		&i.ScrollDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmbed = `-- name: DeleteEmbed :exec
DELETE FROM embeds WHERE id = $1
`

func (q *Queries) DeleteEmbed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmbed, id)
	return err
}

const getEmbedByID = `-- name: GetEmbedByID :one
SELECT id, product_id, name, slug, layout, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, show_header, header_text_color, subtitle, max_items, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_opacity, rows, width_percent, auto_scroll, scroll_direction, created_at, updated_at FROM embeds WHERE id = $1
`

func (q *Queries) GetEmbedByID(ctx context.Context, id uuid.UUID) (Embed, error) {
	row := q.db.QueryRow(ctx, getEmbedByID, id)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Layout,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.ShowHeader,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.MaxItems,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgOpacity,
		&i.Rows,
		&i.WidthPercent,
		&i.AutoScroll,
		&i.ScrollDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmbedBySlug = `-- name: GetEmbedBySlug :one
SELECT id, product_id, name, slug, layout, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, show_header, header_text_color, subtitle, max_items, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_opacity, rows, width_percent, auto_scroll, scroll_direction, created_at, updated_at FROM embeds WHERE slug = $1
`

func (q *Queries) GetEmbedBySlug(ctx context.Context, slug string) (Embed, error) {
	row := q.db.QueryRow(ctx, getEmbedBySlug, slug)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Layout,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.ShowHeader,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.MaxItems,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgOpacity,
		&i.Rows,
		&i.WidthPercent,
		&i.AutoScroll,
		&i.ScrollDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmbedsByProductID = `-- name: ListEmbedsByProductID :many
SELECT id, product_id, name, slug, layout, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, show_header, header_text_color, subtitle, max_items, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_opacity, rows, width_percent, auto_scroll, scroll_direction, created_at, updated_at FROM embeds WHERE product_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListEmbedsByProductID(ctx context.Context, productID uuid.UUID) ([]Embed, error) {
	rows, err := q.db.Query(ctx, listEmbedsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Embed{}
	for rows.Next() {
		var i Embed
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.Layout,
			&i.Theme,
			&i.BorderRadius,
			&i.CardSpacing,
			&i.ShowPlatformIcon,
			&i.ShowBranding,
			&i.BgColor,
			&i.TransparentBg,
			&i.ShowHeader,
			&i.HeaderTextColor,
			&i.Subtitle,
			&i.MaxItems,
			&i.VisibleCount,
			&i.CardSize,
			&i.CardHeight,
			&i.TextFontSize,
			&i.TextFont,
			&i.TextBold,
			&i.BgOpacity,
			&i.Rows,
			&i.WidthPercent,
			&i.AutoScroll,
			&i.ScrollDirection,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmbed = `-- name: UpdateEmbed :one
UPDATE embeds SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, slug, layout, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, show_header, header_text_color, subtitle, max_items, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_opacity, rows, width_percent, auto_scroll, scroll_direction, created_at, updated_at
`

type UpdateEmbedParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateEmbed(ctx context.Context, arg UpdateEmbedParams) (Embed, error) {
	row := q.db.QueryRow(ctx, updateEmbed, arg.ID, arg.Name)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Layout,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.ShowHeader,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.MaxItems,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgOpacity,
		&i.Rows,
		&i.WidthPercent,
		&i.AutoScroll,
		&i.ScrollDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmbedConfig = `-- name: UpdateEmbedConfig :one
UPDATE embeds SET
    layout = $2,
    theme = $3,
    border_radius = $4,
    card_spacing = $5,
    show_platform_icon = $6,
    show_branding = $7,
    bg_color = $8,
    transparent_bg = $9,
    show_header = $10,
    header_text_color = $11,
    subtitle = $12,
    max_items = $13,
    visible_count = $14,
    card_size = $15,
    card_height = $16,
    text_font_size = $17,
    text_font = $18,
    text_bold = $19,
    bg_opacity = $20,
    rows = $21,
    width_percent = $22,
    auto_scroll = $23,
    scroll_direction = $24,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, slug, layout, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, show_header, header_text_color, subtitle, max_items, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_opacity, rows, width_percent, auto_scroll, scroll_direction, created_at, updated_at
`

type UpdateEmbedConfigParams struct {
	ID               uuid.UUID   `json:"id"`
	Layout           string      `json:"layout"`
	Theme            pgtype.Text `json:"theme"`
	BorderRadius     pgtype.Int4 `json:"border_radius"`
	CardSpacing      pgtype.Int4 `json:"card_spacing"`
	ShowPlatformIcon pgtype.Bool `json:"show_platform_icon"`
	ShowBranding     pgtype.Bool `json:"show_branding"`
	BgColor          pgtype.Text `json:"bg_color"`
	TransparentBg    pgtype.Bool `json:"transparent_bg"`
	ShowHeader       pgtype.Bool `json:"show_header"`
	HeaderTextColor  pgtype.Text `json:"header_text_color"`
	Subtitle         pgtype.Text `json:"subtitle"`
	MaxItems         pgtype.Int4 `json:"max_items"`
	VisibleCount     pgtype.Int4 `json:"visible_count"`
	CardSize         pgtype.Int4 `json:"card_size"`
	CardHeight       pgtype.Int4 `json:"card_height"`
	TextFontSize     pgtype.Int4 `json:"text_font_size"`
	TextFont         pgtype.Text `json:"text_font"`
	TextBold         pgtype.Bool `json:"text_bold"`
	BgOpacity        pgtype.Int4 `json:"bg_opacity"`
	Rows             pgtype.Int4 `json:"rows"`
	WidthPercent     pgtype.Int4 `json:"width_percent"`
	AutoScroll       pgtype.Bool `json:"auto_scroll"`
	ScrollDirection  pgtype.Text `json:"scroll_direction"`
}

func (q *Queries) UpdateEmbedConfig(ctx context.Context, arg UpdateEmbedConfigParams) (Embed, error) {
	row := q.db.QueryRow(ctx, updateEmbedConfig,
		arg.ID,
		arg.Layout,
		arg.Theme,
		arg.BorderRadius,
		arg.CardSpacing,
		arg.ShowPlatformIcon,
		arg.ShowBranding,
		arg.BgColor,
		arg.TransparentBg,
		arg.ShowHeader,
		arg.HeaderTextColor,
		arg.Subtitle,
		arg.MaxItems,
		arg.VisibleCount,
		arg.CardSize,
		arg.CardHeight,
		arg.TextFontSize,
		arg.TextFont,
		arg.TextBold,
		arg.BgOpacity,
		arg.Rows,
		arg.WidthPercent,
		arg.AutoScroll,
		arg.ScrollDirection,
	)
	var i Embed
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Layout,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.ShowHeader,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.MaxItems,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgOpacity,
		&i.Rows,
		&i.WidthPercent,
		&i.AutoScroll,
		&i.ScrollDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
