// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embed_proofs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProofToEmbed = `-- name: AddProofToEmbed :one
INSERT INTO embed_proofs (embed_id, proof_id, display_order)
VALUES ($1, $2, $3)
ON CONFLICT (embed_id, proof_id) DO NOTHING
RETURNING id, embed_id, proof_id, display_order
`

type AddProofToEmbedParams struct {
	EmbedID      uuid.UUID   `json:"embed_id"`
	ProofID      uuid.UUID   `json:"proof_id"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

func (q *Queries) AddProofToEmbed(ctx context.Context, arg AddProofToEmbedParams) (EmbedProof, error) {
	row := q.db.QueryRow(ctx, addProofToEmbed, arg.EmbedID, arg.ProofID, arg.DisplayOrder)
	var i EmbedProof
	err := row.Scan(
		&i.ID,
		&i.EmbedID,
		&i.ProofID,
		&i.DisplayOrder,
	)
	return i, err
}

const listProofsByEmbedID = `-- name: ListProofsByEmbedID :many
SELECT p.id, p.product_id, p.status, p.collection_method, p.source_platform, p.source_url, p.content_type, p.content_text, p.content_image_url, p.author_name, p.author_title, p.author_avatar_url, p.proof_date, p.linked_version_id, p.is_featured, p.display_order, p.created_at, p.updated_at, p.author_email, p.author_handle, p.rating, p.video_url, p.video_duration_seconds, p.submitted_ip_hash, ep.display_order as embed_display_order FROM embed_proofs ep
JOIN proofs p ON p.id = ep.proof_id
WHERE ep.embed_id = $1
ORDER BY ep.display_order ASC, p.created_at DESC
`

type ListProofsByEmbedIDRow struct {
	ID                   uuid.UUID        `json:"id"`
	ProductID            uuid.UUID        `json:"product_id"`
	Status               ProofStatus      `json:"status"`
	CollectionMethod     CollectionMethod `json:"collection_method"`
	SourcePlatform       SourcePlatform   `json:"source_platform"`
	SourceUrl            pgtype.Text      `json:"source_url"`
	ContentType          ContentType      `json:"content_type"`
	ContentText          pgtype.Text      `json:"content_text"`
	ContentImageUrl      pgtype.Text      `json:"content_image_url"`
	AuthorName           string           `json:"author_name"`
	AuthorTitle          pgtype.Text      `json:"author_title"`
	AuthorAvatarUrl      pgtype.Text      `json:"author_avatar_url"`
	ProofDate            pgtype.Date      `json:"proof_date"`
	LinkedVersionID      pgtype.UUID      `json:"linked_version_id"`
	IsFeatured           bool             `json:"is_featured"`
	DisplayOrder         int32            `json:"display_order"`
	CreatedAt            time.Time        `json:"created_at"`
	UpdatedAt            time.Time        `json:"updated_at"`
	AuthorEmail          pgtype.Text      `json:"author_email"`
	AuthorHandle         pgtype.Text      `json:"author_handle"`
	Rating               pgtype.Int4      `json:"rating"`
	VideoUrl             pgtype.Text      `json:"video_url"`
	VideoDurationSeconds pgtype.Int4      `json:"video_duration_seconds"`
	SubmittedIpHash      pgtype.Text      `json:"submitted_ip_hash"`
	EmbedDisplayOrder    pgtype.Int4      `json:"embed_display_order"`
}

func (q *Queries) ListProofsByEmbedID(ctx context.Context, embedID uuid.UUID) ([]ListProofsByEmbedIDRow, error) {
	rows, err := q.db.Query(ctx, listProofsByEmbedID, embedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProofsByEmbedIDRow{}
	for rows.Next() {
		var i ListProofsByEmbedIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Status,
			&i.CollectionMethod,
			&i.SourcePlatform,
			&i.SourceUrl,
			&i.ContentType,
			&i.ContentText,
			&i.ContentImageUrl,
			&i.AuthorName,
			&i.AuthorTitle,
			&i.AuthorAvatarUrl,
			&i.ProofDate,
			&i.LinkedVersionID,
			&i.IsFeatured,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorEmail,
			&i.AuthorHandle,
			&i.Rating,
			&i.VideoUrl,
			&i.VideoDurationSeconds,
			&i.SubmittedIpHash,
			&i.EmbedDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProofFromEmbed = `-- name: RemoveProofFromEmbed :exec
DELETE FROM embed_proofs WHERE embed_id = $1 AND proof_id = $2
`

type RemoveProofFromEmbedParams struct {
	EmbedID uuid.UUID `json:"embed_id"`
	ProofID uuid.UUID `json:"proof_id"`
}

func (q *Queries) RemoveProofFromEmbed(ctx context.Context, arg RemoveProofFromEmbedParams) error {
	_, err := q.db.Exec(ctx, removeProofFromEmbed, arg.EmbedID, arg.ProofID)
	return err
}

const updateEmbedProofOrder = `-- name: UpdateEmbedProofOrder :exec
UPDATE embed_proofs SET display_order = $3
WHERE embed_id = $1 AND proof_id = $2
`

type UpdateEmbedProofOrderParams struct {
	EmbedID      uuid.UUID   `json:"embed_id"`
	ProofID      uuid.UUID   `json:"proof_id"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

func (q *Queries) UpdateEmbedProofOrder(ctx context.Context, arg UpdateEmbedProofOrderParams) error {
	_, err := q.db.Exec(ctx, updateEmbedProofOrder, arg.EmbedID, arg.ProofID, arg.DisplayOrder)
	return err
}
