// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: launch_versions.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countVersionsByProductID = `-- name: CountVersionsByProductID :one
SELECT COUNT(*) FROM launch_versions WHERE product_id = $1
`

func (q *Queries) CountVersionsByProductID(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVersionsByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVersion = `-- name: CreateVersion :one
INSERT INTO launch_versions (product_id, version_number, version_label, title, launch_type, platforms, content, launch_notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, product_id, version_number, version_label, title, launch_type, platforms, content, created_at, launch_notes
`

type CreateVersionParams struct {
	ProductID     uuid.UUID       `json:"product_id"`
	VersionNumber int32           `json:"version_number"`
	VersionLabel  string          `json:"version_label"`
	Title         string          `json:"title"`
	LaunchType    LaunchType      `json:"launch_type"`
	Platforms     json.RawMessage `json:"platforms"`
	Content       json.RawMessage `json:"content"`
	LaunchNotes   pgtype.Text     `json:"launch_notes"`
}

func (q *Queries) CreateVersion(ctx context.Context, arg CreateVersionParams) (LaunchVersion, error) {
	row := q.db.QueryRow(ctx, createVersion,
		arg.ProductID,
		arg.VersionNumber,
		arg.VersionLabel,
		arg.Title,
		arg.LaunchType,
		arg.Platforms,
		arg.Content,
		arg.LaunchNotes,
	)
	var i LaunchVersion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VersionNumber,
		&i.VersionLabel,
		&i.Title,
		&i.LaunchType,
		&i.Platforms,
		&i.Content,
		&i.CreatedAt,
		&i.LaunchNotes,
	)
	return i, err
}

const getMaxVersionNumber = `-- name: GetMaxVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::integer AS max_version_number
FROM launch_versions
WHERE product_id = $1
`

func (q *Queries) GetMaxVersionNumber(ctx context.Context, productID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxVersionNumber, productID)
	var max_version_number int32
	err := row.Scan(&max_version_number)
	return max_version_number, err
}

const getVersionByID = `-- name: GetVersionByID :one
SELECT id, product_id, version_number, version_label, title, launch_type, platforms, content, created_at, launch_notes FROM launch_versions WHERE id = $1
`

func (q *Queries) GetVersionByID(ctx context.Context, id uuid.UUID) (LaunchVersion, error) {
	row := q.db.QueryRow(ctx, getVersionByID, id)
	var i LaunchVersion
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VersionNumber,
		&i.VersionLabel,
		&i.Title,
		&i.LaunchType,
		&i.Platforms,
		&i.Content,
		&i.CreatedAt,
		&i.LaunchNotes,
	)
	return i, err
}

const listVersionsByProductID = `-- name: ListVersionsByProductID :many
SELECT id, product_id, version_number, version_label, title, launch_type, platforms, launch_notes, created_at
FROM launch_versions
WHERE product_id = $1
ORDER BY created_at DESC
`

type ListVersionsByProductIDRow struct {
	ID            uuid.UUID       `json:"id"`
	ProductID     uuid.UUID       `json:"product_id"`
	VersionNumber int32           `json:"version_number"`
	VersionLabel  string          `json:"version_label"`
	Title         string          `json:"title"`
	LaunchType    LaunchType      `json:"launch_type"`
	Platforms     json.RawMessage `json:"platforms"`
	LaunchNotes   pgtype.Text     `json:"launch_notes"`
	CreatedAt     time.Time       `json:"created_at"`
}

func (q *Queries) ListVersionsByProductID(ctx context.Context, productID uuid.UUID) ([]ListVersionsByProductIDRow, error) {
	rows, err := q.db.Query(ctx, listVersionsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVersionsByProductIDRow{}
	for rows.Next() {
		var i ListVersionsByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VersionNumber,
			&i.VersionLabel,
			&i.Title,
			&i.LaunchType,
			&i.Platforms,
			&i.LaunchNotes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
