// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: launch_drafts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDraftsThisMonth = `-- name: CountDraftsThisMonth :one
SELECT COUNT(*) FROM launch_drafts
WHERE product_id IN (SELECT id FROM products WHERE user_id = $1)
AND created_at >= date_trunc('month', now())
`

func (q *Queries) CountDraftsThisMonth(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDraftsThisMonth, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDraftByProductID = `-- name: DeleteDraftByProductID :exec
DELETE FROM launch_drafts WHERE product_id = $1
`

func (q *Queries) DeleteDraftByProductID(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraftByProductID, productID)
	return err
}

const getDraftByProductID = `-- name: GetDraftByProductID :one
SELECT id, product_id, launch_type, platforms, content, created_at, updated_at, launch_notes FROM launch_drafts WHERE product_id = $1
`

func (q *Queries) GetDraftByProductID(ctx context.Context, productID uuid.UUID) (LaunchDraft, error) {
	row := q.db.QueryRow(ctx, getDraftByProductID, productID)
	var i LaunchDraft
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LaunchType,
		&i.Platforms,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LaunchNotes,
	)
	return i, err
}

const updateDraftContent = `-- name: UpdateDraftContent :one
UPDATE launch_drafts
SET content = $2, updated_at = now()
WHERE product_id = $1
RETURNING id, product_id, launch_type, platforms, content, created_at, updated_at, launch_notes
`

type UpdateDraftContentParams struct {
	ProductID uuid.UUID       `json:"product_id"`
	Content   json.RawMessage `json:"content"`
}

func (q *Queries) UpdateDraftContent(ctx context.Context, arg UpdateDraftContentParams) (LaunchDraft, error) {
	row := q.db.QueryRow(ctx, updateDraftContent, arg.ProductID, arg.Content)
	var i LaunchDraft
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LaunchType,
		&i.Platforms,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LaunchNotes,
	)
	return i, err
}

const upsertDraft = `-- name: UpsertDraft :one
INSERT INTO launch_drafts (product_id, launch_type, platforms, content, launch_notes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (product_id) DO UPDATE
SET launch_type = EXCLUDED.launch_type,
    platforms = EXCLUDED.platforms,
    content = EXCLUDED.content,
    launch_notes = EXCLUDED.launch_notes,
    updated_at = now()
RETURNING id, product_id, launch_type, platforms, content, created_at, updated_at, launch_notes
`

type UpsertDraftParams struct {
	ProductID   uuid.UUID       `json:"product_id"`
	LaunchType  LaunchType      `json:"launch_type"`
	Platforms   json.RawMessage `json:"platforms"`
	Content     json.RawMessage `json:"content"`
	LaunchNotes pgtype.Text     `json:"launch_notes"`
}

func (q *Queries) UpsertDraft(ctx context.Context, arg UpsertDraftParams) (LaunchDraft, error) {
	row := q.db.QueryRow(ctx, upsertDraft,
		arg.ProductID,
		arg.LaunchType,
		arg.Platforms,
		arg.Content,
		arg.LaunchNotes,
	)
	var i LaunchDraft
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.LaunchType,
		&i.Platforms,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LaunchNotes,
	)
	return i, err
}
