// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CollectionMethod string

const (
	CollectionMethodManual CollectionMethod = "manual"
	CollectionMethodForm   CollectionMethod = "form"
)

func (e *CollectionMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectionMethod(s)
	case string:
		*e = CollectionMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectionMethod: %T", src)
	}
	return nil
}

type NullCollectionMethod struct {
	CollectionMethod CollectionMethod `json:"collection_method"`
	Valid            bool             `json:"valid"` // Valid is true if CollectionMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectionMethod) Scan(value interface{}) error {
	if value == nil {
		ns.CollectionMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectionMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectionMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectionMethod), nil
}

type ContentType string

const (
	ContentTypeText  ContentType = "text"
	ContentTypeImage ContentType = "image"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type LaunchType string

const (
	LaunchTypeInitial       LaunchType = "initial"
	LaunchTypeFeatureUpdate LaunchType = "feature_update"
	LaunchTypeMajorUpdate   LaunchType = "major_update"
)

func (e *LaunchType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LaunchType(s)
	case string:
		*e = LaunchType(s)
	default:
		return fmt.Errorf("unsupported scan type for LaunchType: %T", src)
	}
	return nil
}

type NullLaunchType struct {
	LaunchType LaunchType `json:"launch_type"`
	Valid      bool       `json:"valid"` // Valid is true if LaunchType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLaunchType) Scan(value interface{}) error {
	if value == nil {
		ns.LaunchType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LaunchType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLaunchType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LaunchType), nil
}

type ProofStatus string

const (
	ProofStatusApproved ProofStatus = "approved"
	ProofStatusPending  ProofStatus = "pending"
	ProofStatusRejected ProofStatus = "rejected"
)

func (e *ProofStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProofStatus(s)
	case string:
		*e = ProofStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProofStatus: %T", src)
	}
	return nil
}

type NullProofStatus struct {
	ProofStatus ProofStatus `json:"proof_status"`
	Valid       bool        `json:"valid"` // Valid is true if ProofStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProofStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProofStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProofStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProofStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProofStatus), nil
}

type SourcePlatform string

const (
	SourcePlatformProductHunt  SourcePlatform = "product_hunt"
	SourcePlatformReddit       SourcePlatform = "reddit"
	SourcePlatformTwitter      SourcePlatform = "twitter"
	SourcePlatformHackernews   SourcePlatform = "hackernews"
	SourcePlatformIndiehackers SourcePlatform = "indiehackers"
	SourcePlatformDirect       SourcePlatform = "direct"
	SourcePlatformOther        SourcePlatform = "other"
)

func (e *SourcePlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourcePlatform(s)
	case string:
		*e = SourcePlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for SourcePlatform: %T", src)
	}
	return nil
}

type NullSourcePlatform struct {
	SourcePlatform SourcePlatform `json:"source_platform"`
	Valid          bool           `json:"valid"` // Valid is true if SourcePlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourcePlatform) Scan(value interface{}) error {
	if value == nil {
		ns.SourcePlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourcePlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourcePlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourcePlatform), nil
}

type UserPlan string

const (
	UserPlanFree     UserPlan = "free"
	UserPlanPro      UserPlan = "pro"
	UserPlanBusiness UserPlan = "business"
)

func (e *UserPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserPlan(s)
	case string:
		*e = UserPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for UserPlan: %T", src)
	}
	return nil
}

type NullUserPlan struct {
	UserPlan UserPlan `json:"user_plan"`
	Valid    bool     `json:"valid"` // Valid is true if UserPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserPlan) Scan(value interface{}) error {
	if value == nil {
		ns.UserPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserPlan), nil
}

type WidgetTheme string

const (
	WidgetThemeDark  WidgetTheme = "dark"
	WidgetThemeLight WidgetTheme = "light"
	WidgetThemeDim   WidgetTheme = "dim"
	WidgetThemeGray  WidgetTheme = "gray"
)

func (e *WidgetTheme) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WidgetTheme(s)
	case string:
		*e = WidgetTheme(s)
	default:
		return fmt.Errorf("unsupported scan type for WidgetTheme: %T", src)
	}
	return nil
}

type NullWidgetTheme struct {
	WidgetTheme WidgetTheme `json:"widget_theme"`
	Valid       bool        `json:"valid"` // Valid is true if WidgetTheme is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWidgetTheme) Scan(value interface{}) error {
	if value == nil {
		ns.WidgetTheme, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WidgetTheme.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWidgetTheme) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WidgetTheme), nil
}

type LaunchDraft struct {
	ID          uuid.UUID       `json:"id"`
	ProductID   uuid.UUID       `json:"product_id"`
	LaunchType  LaunchType      `json:"launch_type"`
	Platforms   json.RawMessage `json:"platforms"`
	Content     json.RawMessage `json:"content"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	LaunchNotes pgtype.Text     `json:"launch_notes"`
}

type LaunchVersion struct {
	ID            uuid.UUID       `json:"id"`
	ProductID     uuid.UUID       `json:"product_id"`
	VersionNumber int32           `json:"version_number"`
	VersionLabel  string          `json:"version_label"`
	Title         string          `json:"title"`
	LaunchType    LaunchType      `json:"launch_type"`
	Platforms     json.RawMessage `json:"platforms"`
	Content       json.RawMessage `json:"content"`
	CreatedAt     time.Time       `json:"created_at"`
	LaunchNotes   pgtype.Text     `json:"launch_notes"`
}

type Product struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	Url             pgtype.Text `json:"url"`
	Description     pgtype.Text `json:"description"`
	DescriptionLong pgtype.Text `json:"description_long"`
	TargetAudience  pgtype.Text `json:"target_audience"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	LogoUrl         pgtype.Text `json:"logo_url"`
}

type Proof struct {
	ID               uuid.UUID        `json:"id"`
	ProductID        uuid.UUID        `json:"product_id"`
	Status           ProofStatus      `json:"status"`
	CollectionMethod CollectionMethod `json:"collection_method"`
	SourcePlatform   SourcePlatform   `json:"source_platform"`
	SourceUrl        pgtype.Text      `json:"source_url"`
	ContentType      ContentType      `json:"content_type"`
	ContentText      pgtype.Text      `json:"content_text"`
	ContentImageUrl  pgtype.Text      `json:"content_image_url"`
	AuthorName       string           `json:"author_name"`
	AuthorTitle      pgtype.Text      `json:"author_title"`
	AuthorAvatarUrl  pgtype.Text      `json:"author_avatar_url"`
	ProofDate        pgtype.Date      `json:"proof_date"`
	LinkedVersionID  pgtype.UUID      `json:"linked_version_id"`
	IsFeatured       bool             `json:"is_featured"`
	DisplayOrder     int32            `json:"display_order"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
}

type ProofTag struct {
	ID      uuid.UUID `json:"id"`
	ProofID uuid.UUID `json:"proof_id"`
	Tag     string    `json:"tag"`
}

type Space struct {
	ID               uuid.UUID   `json:"id"`
	ProductID        uuid.UUID   `json:"product_id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	Theme            WidgetTheme `json:"theme"`
	MaxItems         int32       `json:"max_items"`
	ShowPlatformIcon bool        `json:"show_platform_icon"`
	BorderRadius     int32       `json:"border_radius"`
	CardSpacing      int32       `json:"card_spacing"`
	ShowBranding     bool        `json:"show_branding"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	VisibleCount     int32       `json:"visible_count"`
	CardSize         int32       `json:"card_size"`
	CardHeight       int32       `json:"card_height"`
	TextFontSize     int32       `json:"text_font_size"`
	TextFont         string      `json:"text_font"`
	TextBold         bool        `json:"text_bold"`
	BgColor          string      `json:"bg_color"`
	BgOpacity        int32       `json:"bg_opacity"`
}

type SpaceProof struct {
	ID           uuid.UUID `json:"id"`
	SpaceID      uuid.UUID `json:"space_id"`
	ProofID      uuid.UUID `json:"proof_id"`
	DisplayOrder int32     `json:"display_order"`
}

type User struct {
	ID                   uuid.UUID   `json:"id"`
	ClerkID              string      `json:"clerk_id"`
	Email                string      `json:"email"`
	Name                 string      `json:"name"`
	AvatarUrl            pgtype.Text `json:"avatar_url"`
	Plan                 UserPlan    `json:"plan"`
	StripeCustomerID     pgtype.Text `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
	CreatedAt            time.Time   `json:"created_at"`
	UpdatedAt            time.Time   `json:"updated_at"`
}

type ViewEvent struct {
	ID         uuid.UUID   `json:"id"`
	EntityType string      `json:"entity_type"`
	EntityID   uuid.UUID   `json:"entity_id"`
	ProductID  uuid.UUID   `json:"product_id"`
	Referrer   pgtype.Text `json:"referrer"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Wall struct {
	ID               uuid.UUID   `json:"id"`
	ProductID        uuid.UUID   `json:"product_id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Theme            WidgetTheme `json:"theme"`
	BorderRadius     int32       `json:"border_radius"`
	CardSpacing      int32       `json:"card_spacing"`
	ShowPlatformIcon bool        `json:"show_platform_icon"`
	ShowBranding     bool        `json:"show_branding"`
}

type WallProof struct {
	ID           uuid.UUID `json:"id"`
	WallID       uuid.UUID `json:"wall_id"`
	ProofID      uuid.UUID `json:"proof_id"`
	DisplayOrder int32     `json:"display_order"`
}

type WidgetConfig struct {
	ID               uuid.UUID   `json:"id"`
	ProductID        uuid.UUID   `json:"product_id"`
	Theme            WidgetTheme `json:"theme"`
	MaxItems         int32       `json:"max_items"`
	ShowPlatformIcon bool        `json:"show_platform_icon"`
	BorderRadius     int32       `json:"border_radius"`
	CardSpacing      int32       `json:"card_spacing"`
	ShowBranding     bool        `json:"show_branding"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}
