// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (user_id, name, slug, url, description, logo_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, slug, url, description, description_long, target_audience, created_at, updated_at, logo_url
`

type CreateProductParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Url         pgtype.Text `json:"url"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Url,
		arg.Description,
		arg.LogoUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.DescriptionLong,
		&i.TargetAudience,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, user_id, name, slug, url, description, description_long, target_audience, created_at, updated_at, logo_url FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.DescriptionLong,
		&i.TargetAudience,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
	)
	return i, err
}

const listProductsByUserID = `-- name: ListProductsByUserID :many
SELECT id, user_id, name, slug, url, description, description_long, target_audience, created_at, updated_at, logo_url FROM products WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProductsByUserID(ctx context.Context, userID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Url,
			&i.Description,
			&i.DescriptionLong,
			&i.TargetAudience,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, url = $3, description = $4, description_long = $5, target_audience = $6, logo_url = $7, updated_at = now()
WHERE id = $1
RETURNING id, user_id, name, slug, url, description, description_long, target_audience, created_at, updated_at, logo_url
`

type UpdateProductParams struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	Url             pgtype.Text `json:"url"`
	Description     pgtype.Text `json:"description"`
	DescriptionLong pgtype.Text `json:"description_long"`
	TargetAudience  pgtype.Text `json:"target_audience"`
	LogoUrl         pgtype.Text `json:"logo_url"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Description,
		arg.DescriptionLong,
		arg.TargetAudience,
		arg.LogoUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.DescriptionLong,
		&i.TargetAudience,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
	)
	return i, err
}
