// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proof_tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTagToProof = `-- name: AddTagToProof :one
INSERT INTO proof_tags (proof_id, tag)
VALUES ($1, $2)
ON CONFLICT (proof_id, tag) DO NOTHING
RETURNING id, proof_id, tag
`

type AddTagToProofParams struct {
	ProofID uuid.UUID `json:"proof_id"`
	Tag     string    `json:"tag"`
}

func (q *Queries) AddTagToProof(ctx context.Context, arg AddTagToProofParams) (ProofTag, error) {
	row := q.db.QueryRow(ctx, addTagToProof, arg.ProofID, arg.Tag)
	var i ProofTag
	err := row.Scan(&i.ID, &i.ProofID, &i.Tag)
	return i, err
}

const listDistinctTagsByProductID = `-- name: ListDistinctTagsByProductID :many
SELECT DISTINCT pt.tag FROM proof_tags pt
JOIN proofs p ON p.id = pt.proof_id
WHERE p.product_id = $1
ORDER BY pt.tag
`

func (q *Queries) ListDistinctTagsByProductID(ctx context.Context, productID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctTagsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByProofID = `-- name: ListTagsByProofID :many
SELECT id, proof_id, tag FROM proof_tags WHERE proof_id = $1 ORDER BY tag
`

func (q *Queries) ListTagsByProofID(ctx context.Context, proofID uuid.UUID) ([]ProofTag, error) {
	rows, err := q.db.Query(ctx, listTagsByProofID, proofID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProofTag{}
	for rows.Next() {
		var i ProofTag
		if err := rows.Scan(&i.ID, &i.ProofID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromProof = `-- name: RemoveTagFromProof :exec
DELETE FROM proof_tags WHERE proof_id = $1 AND tag = $2
`

type RemoveTagFromProofParams struct {
	ProofID uuid.UUID `json:"proof_id"`
	Tag     string    `json:"tag"`
}

func (q *Queries) RemoveTagFromProof(ctx context.Context, arg RemoveTagFromProofParams) error {
	_, err := q.db.Exec(ctx, removeTagFromProof, arg.ProofID, arg.Tag)
	return err
}
