// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proof_page.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProofToProofPage = `-- name: AddProofToProofPage :exec
INSERT INTO proof_page_proofs (product_id, proof_id, display_order)
VALUES ($1, $2, $3)
ON CONFLICT (product_id, proof_id) DO NOTHING
`

type AddProofToProofPageParams struct {
	ProductID    uuid.UUID   `json:"product_id"`
	ProofID      uuid.UUID   `json:"proof_id"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

func (q *Queries) AddProofToProofPage(ctx context.Context, arg AddProofToProofPageParams) error {
	_, err := q.db.Exec(ctx, addProofToProofPage, arg.ProductID, arg.ProofID, arg.DisplayOrder)
	return err
}

const getProofPageConfig = `-- name: GetProofPageConfig :one
SELECT id, name, slug, url, description, logo_url,
       proof_page_title, proof_page_subtitle, proof_page_theme,
       proof_page_show_form, proof_page_form_heading, proof_page_show_branding,
       proof_page_cta_text, proof_page_cta_url
FROM products WHERE id = $1
`

type GetProofPageConfigRow struct {
	ID                    uuid.UUID   `json:"id"`
	Name                  string      `json:"name"`
	Slug                  string      `json:"slug"`
	Url                   pgtype.Text `json:"url"`
	Description           pgtype.Text `json:"description"`
	LogoUrl               pgtype.Text `json:"logo_url"`
	ProofPageTitle        pgtype.Text `json:"proof_page_title"`
	ProofPageSubtitle     pgtype.Text `json:"proof_page_subtitle"`
	ProofPageTheme        pgtype.Text `json:"proof_page_theme"`
	ProofPageShowForm     pgtype.Bool `json:"proof_page_show_form"`
	ProofPageFormHeading  pgtype.Text `json:"proof_page_form_heading"`
	ProofPageShowBranding pgtype.Bool `json:"proof_page_show_branding"`
	ProofPageCtaText      pgtype.Text `json:"proof_page_cta_text"`
	ProofPageCtaUrl       pgtype.Text `json:"proof_page_cta_url"`
}

func (q *Queries) GetProofPageConfig(ctx context.Context, id uuid.UUID) (GetProofPageConfigRow, error) {
	row := q.db.QueryRow(ctx, getProofPageConfig, id)
	var i GetProofPageConfigRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.LogoUrl,
		&i.ProofPageTitle,
		&i.ProofPageSubtitle,
		&i.ProofPageTheme,
		&i.ProofPageShowForm,
		&i.ProofPageFormHeading,
		&i.ProofPageShowBranding,
		&i.ProofPageCtaText,
		&i.ProofPageCtaUrl,
	)
	return i, err
}

const getPublicProofPageData = `-- name: GetPublicProofPageData :one
SELECT id, name, slug, url, description, logo_url,
       proof_page_title, proof_page_subtitle, proof_page_theme,
       proof_page_show_form, proof_page_form_heading, proof_page_show_branding,
       proof_page_cta_text, proof_page_cta_url
FROM products WHERE slug = $1
`

type GetPublicProofPageDataRow struct {
	ID                    uuid.UUID   `json:"id"`
	Name                  string      `json:"name"`
	Slug                  string      `json:"slug"`
	Url                   pgtype.Text `json:"url"`
	Description           pgtype.Text `json:"description"`
	LogoUrl               pgtype.Text `json:"logo_url"`
	ProofPageTitle        pgtype.Text `json:"proof_page_title"`
	ProofPageSubtitle     pgtype.Text `json:"proof_page_subtitle"`
	ProofPageTheme        pgtype.Text `json:"proof_page_theme"`
	ProofPageShowForm     pgtype.Bool `json:"proof_page_show_form"`
	ProofPageFormHeading  pgtype.Text `json:"proof_page_form_heading"`
	ProofPageShowBranding pgtype.Bool `json:"proof_page_show_branding"`
	ProofPageCtaText      pgtype.Text `json:"proof_page_cta_text"`
	ProofPageCtaUrl       pgtype.Text `json:"proof_page_cta_url"`
}

func (q *Queries) GetPublicProofPageData(ctx context.Context, slug string) (GetPublicProofPageDataRow, error) {
	row := q.db.QueryRow(ctx, getPublicProofPageData, slug)
	var i GetPublicProofPageDataRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.LogoUrl,
		&i.ProofPageTitle,
		&i.ProofPageSubtitle,
		&i.ProofPageTheme,
		&i.ProofPageShowForm,
		&i.ProofPageFormHeading,
		&i.ProofPageShowBranding,
		&i.ProofPageCtaText,
		&i.ProofPageCtaUrl,
	)
	return i, err
}

const listProofPageProofs = `-- name: ListProofPageProofs :many
SELECT p.id, p.product_id, p.status, p.collection_method, p.source_platform, p.source_url, p.content_type, p.content_text, p.content_image_url, p.author_name, p.author_title, p.author_avatar_url, p.proof_date, p.linked_version_id, p.is_featured, p.display_order, p.created_at, p.updated_at, p.author_email, p.author_handle, p.rating, p.video_url, p.video_duration_seconds, p.submitted_ip_hash, pp.display_order as page_display_order FROM proofs p
JOIN proof_page_proofs pp ON p.id = pp.proof_id
WHERE pp.product_id = $1 AND p.status = 'approved'
ORDER BY pp.display_order ASC, p.created_at DESC
`

type ListProofPageProofsRow struct {
	ID                   uuid.UUID        `json:"id"`
	ProductID            uuid.UUID        `json:"product_id"`
	Status               ProofStatus      `json:"status"`
	CollectionMethod     CollectionMethod `json:"collection_method"`
	SourcePlatform       SourcePlatform   `json:"source_platform"`
	SourceUrl            pgtype.Text      `json:"source_url"`
	ContentType          ContentType      `json:"content_type"`
	ContentText          pgtype.Text      `json:"content_text"`
	ContentImageUrl      pgtype.Text      `json:"content_image_url"`
	AuthorName           string           `json:"author_name"`
	AuthorTitle          pgtype.Text      `json:"author_title"`
	AuthorAvatarUrl      pgtype.Text      `json:"author_avatar_url"`
	ProofDate            pgtype.Date      `json:"proof_date"`
	LinkedVersionID      pgtype.UUID      `json:"linked_version_id"`
	IsFeatured           bool             `json:"is_featured"`
	DisplayOrder         int32            `json:"display_order"`
	CreatedAt            time.Time        `json:"created_at"`
	UpdatedAt            time.Time        `json:"updated_at"`
	AuthorEmail          pgtype.Text      `json:"author_email"`
	AuthorHandle         pgtype.Text      `json:"author_handle"`
	Rating               pgtype.Int4      `json:"rating"`
	VideoUrl             pgtype.Text      `json:"video_url"`
	VideoDurationSeconds pgtype.Int4      `json:"video_duration_seconds"`
	SubmittedIpHash      pgtype.Text      `json:"submitted_ip_hash"`
	PageDisplayOrder     pgtype.Int4      `json:"page_display_order"`
}

func (q *Queries) ListProofPageProofs(ctx context.Context, productID uuid.UUID) ([]ListProofPageProofsRow, error) {
	rows, err := q.db.Query(ctx, listProofPageProofs, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProofPageProofsRow{}
	for rows.Next() {
		var i ListProofPageProofsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Status,
			&i.CollectionMethod,
			&i.SourcePlatform,
			&i.SourceUrl,
			&i.ContentType,
			&i.ContentText,
			&i.ContentImageUrl,
			&i.AuthorName,
			&i.AuthorTitle,
			&i.AuthorAvatarUrl,
			&i.ProofDate,
			&i.LinkedVersionID,
			&i.IsFeatured,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorEmail,
			&i.AuthorHandle,
			&i.Rating,
			&i.VideoUrl,
			&i.VideoDurationSeconds,
			&i.SubmittedIpHash,
			&i.PageDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProofPageProofs = `-- name: ListPublicProofPageProofs :many
SELECT p.id, p.product_id, p.status, p.collection_method, p.source_platform, p.source_url, p.content_type, p.content_text, p.content_image_url, p.author_name, p.author_title, p.author_avatar_url, p.proof_date, p.linked_version_id, p.is_featured, p.display_order, p.created_at, p.updated_at, p.author_email, p.author_handle, p.rating, p.video_url, p.video_duration_seconds, p.submitted_ip_hash FROM proofs p
JOIN proof_page_proofs pp ON p.id = pp.proof_id
WHERE pp.product_id = $1 AND p.status = 'approved'
ORDER BY pp.display_order ASC, p.created_at DESC
`

func (q *Queries) ListPublicProofPageProofs(ctx context.Context, productID uuid.UUID) ([]Proof, error) {
	rows, err := q.db.Query(ctx, listPublicProofPageProofs, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proof{}
	for rows.Next() {
		var i Proof
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Status,
			&i.CollectionMethod,
			&i.SourcePlatform,
			&i.SourceUrl,
			&i.ContentType,
			&i.ContentText,
			&i.ContentImageUrl,
			&i.AuthorName,
			&i.AuthorTitle,
			&i.AuthorAvatarUrl,
			&i.ProofDate,
			&i.LinkedVersionID,
			&i.IsFeatured,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorEmail,
			&i.AuthorHandle,
			&i.Rating,
			&i.VideoUrl,
			&i.VideoDurationSeconds,
			&i.SubmittedIpHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProofFromProofPage = `-- name: RemoveProofFromProofPage :exec
DELETE FROM proof_page_proofs WHERE product_id = $1 AND proof_id = $2
`

type RemoveProofFromProofPageParams struct {
	ProductID uuid.UUID `json:"product_id"`
	ProofID   uuid.UUID `json:"proof_id"`
}

func (q *Queries) RemoveProofFromProofPage(ctx context.Context, arg RemoveProofFromProofPageParams) error {
	_, err := q.db.Exec(ctx, removeProofFromProofPage, arg.ProductID, arg.ProofID)
	return err
}

const updateProofPageConfig = `-- name: UpdateProofPageConfig :exec
UPDATE products SET
  proof_page_title = $2,
  proof_page_subtitle = $3,
  proof_page_theme = $4,
  proof_page_show_form = $5,
  proof_page_form_heading = $6,
  proof_page_show_branding = $7,
  proof_page_cta_text = $8,
  proof_page_cta_url = $9,
  updated_at = NOW()
WHERE id = $1
`

type UpdateProofPageConfigParams struct {
	ID                    uuid.UUID   `json:"id"`
	ProofPageTitle        pgtype.Text `json:"proof_page_title"`
	ProofPageSubtitle     pgtype.Text `json:"proof_page_subtitle"`
	ProofPageTheme        pgtype.Text `json:"proof_page_theme"`
	ProofPageShowForm     pgtype.Bool `json:"proof_page_show_form"`
	ProofPageFormHeading  pgtype.Text `json:"proof_page_form_heading"`
	ProofPageShowBranding pgtype.Bool `json:"proof_page_show_branding"`
	ProofPageCtaText      pgtype.Text `json:"proof_page_cta_text"`
	ProofPageCtaUrl       pgtype.Text `json:"proof_page_cta_url"`
}

func (q *Queries) UpdateProofPageConfig(ctx context.Context, arg UpdateProofPageConfigParams) error {
	_, err := q.db.Exec(ctx, updateProofPageConfig,
		arg.ID,
		arg.ProofPageTitle,
		arg.ProofPageSubtitle,
		arg.ProofPageTheme,
		arg.ProofPageShowForm,
		arg.ProofPageFormHeading,
		arg.ProofPageShowBranding,
		arg.ProofPageCtaText,
		arg.ProofPageCtaUrl,
	)
	return err
}

const updateProofPageProofOrder = `-- name: UpdateProofPageProofOrder :exec
UPDATE proof_page_proofs SET display_order = $3
WHERE product_id = $1 AND proof_id = $2
`

type UpdateProofPageProofOrderParams struct {
	ProductID    uuid.UUID   `json:"product_id"`
	ProofID      uuid.UUID   `json:"proof_id"`
	DisplayOrder pgtype.Int4 `json:"display_order"`
}

func (q *Queries) UpdateProofPageProofOrder(ctx context.Context, arg UpdateProofPageProofOrderParams) error {
	_, err := q.db.Exec(ctx, updateProofPageProofOrder, arg.ProductID, arg.ProofID, arg.DisplayOrder)
	return err
}
