// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proofs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProofsByProductID = `-- name: CountProofsByProductID :one
SELECT COUNT(*) FROM proofs WHERE product_id = $1
`

func (q *Queries) CountProofsByProductID(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProofsByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProof = `-- name: CreateProof :one
INSERT INTO proofs (product_id, status, collection_method, source_platform, source_url, content_type, content_text, content_image_url, author_name, author_title, author_avatar_url, linked_version_id, is_featured, display_order)
VALUES ($1, 'approved', 'manual', $2, $3, $4, $5, $6, $7, $8, $9, $10, false, 0)
RETURNING id, product_id, status, collection_method, source_platform, source_url, content_type, content_text, content_image_url, author_name, author_title, author_avatar_url, proof_date, linked_version_id, is_featured, display_order, created_at, updated_at
`

type CreateProofParams struct {
	ProductID       uuid.UUID      `json:"product_id"`
	SourcePlatform  SourcePlatform `json:"source_platform"`
	SourceUrl       pgtype.Text    `json:"source_url"`
	ContentType     ContentType    `json:"content_type"`
	ContentText     pgtype.Text    `json:"content_text"`
	ContentImageUrl pgtype.Text    `json:"content_image_url"`
	AuthorName      string         `json:"author_name"`
	AuthorTitle     pgtype.Text    `json:"author_title"`
	AuthorAvatarUrl pgtype.Text    `json:"author_avatar_url"`
	LinkedVersionID pgtype.UUID    `json:"linked_version_id"`
}

func (q *Queries) CreateProof(ctx context.Context, arg CreateProofParams) (Proof, error) {
	row := q.db.QueryRow(ctx, createProof,
		arg.ProductID,
		arg.SourcePlatform,
		arg.SourceUrl,
		arg.ContentType,
		arg.ContentText,
		arg.ContentImageUrl,
		arg.AuthorName,
		arg.AuthorTitle,
		arg.AuthorAvatarUrl,
		arg.LinkedVersionID,
	)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Status,
		&i.CollectionMethod,
		&i.SourcePlatform,
		&i.SourceUrl,
		&i.ContentType,
		&i.ContentText,
		&i.ContentImageUrl,
		&i.AuthorName,
		&i.AuthorTitle,
		&i.AuthorAvatarUrl,
		&i.ProofDate,
		&i.LinkedVersionID,
		&i.IsFeatured,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProof = `-- name: DeleteProof :exec
DELETE FROM proofs WHERE id = $1
`

func (q *Queries) DeleteProof(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProof, id)
	return err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, user_id, name, slug, url, description, description_long, target_audience, created_at, updated_at FROM products WHERE slug = $1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.DescriptionLong,
		&i.TargetAudience,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProofByID = `-- name: GetProofByID :one
SELECT id, product_id, status, collection_method, source_platform, source_url, content_type, content_text, content_image_url, author_name, author_title, author_avatar_url, proof_date, linked_version_id, is_featured, display_order, created_at, updated_at FROM proofs WHERE id = $1
`

func (q *Queries) GetProofByID(ctx context.Context, id uuid.UUID) (Proof, error) {
	row := q.db.QueryRow(ctx, getProofByID, id)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Status,
		&i.CollectionMethod,
		&i.SourcePlatform,
		&i.SourceUrl,
		&i.ContentType,
		&i.ContentText,
		&i.ContentImageUrl,
		&i.AuthorName,
		&i.AuthorTitle,
		&i.AuthorAvatarUrl,
		&i.ProofDate,
		&i.LinkedVersionID,
		&i.IsFeatured,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedProofsByProductID = `-- name: ListApprovedProofsByProductID :many
SELECT id, product_id, status, collection_method, source_platform, source_url, content_type, content_text, content_image_url, author_name, author_title, author_avatar_url, proof_date, linked_version_id, is_featured, display_order, created_at, updated_at FROM proofs
WHERE product_id = $1 AND status = 'approved'
ORDER BY is_featured DESC, display_order ASC, created_at DESC
`

func (q *Queries) ListApprovedProofsByProductID(ctx context.Context, productID uuid.UUID) ([]Proof, error) {
	rows, err := q.db.Query(ctx, listApprovedProofsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proof{}
	for rows.Next() {
		var i Proof
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Status,
			&i.CollectionMethod,
			&i.SourcePlatform,
			&i.SourceUrl,
			&i.ContentType,
			&i.ContentText,
			&i.ContentImageUrl,
			&i.AuthorName,
			&i.AuthorTitle,
			&i.AuthorAvatarUrl,
			&i.ProofDate,
			&i.LinkedVersionID,
			&i.IsFeatured,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProofsByProductID = `-- name: ListProofsByProductID :many
SELECT id, product_id, status, collection_method, source_platform, source_url, content_type, content_text, content_image_url, author_name, author_title, author_avatar_url, proof_date, linked_version_id, is_featured, display_order, created_at, updated_at FROM proofs
WHERE product_id = $1
ORDER BY is_featured DESC, display_order ASC, created_at DESC
`

func (q *Queries) ListProofsByProductID(ctx context.Context, productID uuid.UUID) ([]Proof, error) {
	rows, err := q.db.Query(ctx, listProofsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proof{}
	for rows.Next() {
		var i Proof
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Status,
			&i.CollectionMethod,
			&i.SourcePlatform,
			&i.SourceUrl,
			&i.ContentType,
			&i.ContentText,
			&i.ContentImageUrl,
			&i.AuthorName,
			&i.AuthorTitle,
			&i.AuthorAvatarUrl,
			&i.ProofDate,
			&i.LinkedVersionID,
			&i.IsFeatured,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleProofFeatured = `-- name: ToggleProofFeatured :one
UPDATE proofs SET is_featured = NOT is_featured, updated_at = now()
WHERE id = $1
RETURNING id, product_id, status, collection_method, source_platform, source_url, content_type, content_text, content_image_url, author_name, author_title, author_avatar_url, proof_date, linked_version_id, is_featured, display_order, created_at, updated_at
`

func (q *Queries) ToggleProofFeatured(ctx context.Context, id uuid.UUID) (Proof, error) {
	row := q.db.QueryRow(ctx, toggleProofFeatured, id)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Status,
		&i.CollectionMethod,
		&i.SourcePlatform,
		&i.SourceUrl,
		&i.ContentType,
		&i.ContentText,
		&i.ContentImageUrl,
		&i.AuthorName,
		&i.AuthorTitle,
		&i.AuthorAvatarUrl,
		&i.ProofDate,
		&i.LinkedVersionID,
		&i.IsFeatured,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProof = `-- name: UpdateProof :one
UPDATE proofs
SET content_text = $2, content_image_url = $3, author_name = $4, author_title = $5, author_avatar_url = $6, source_platform = $7, source_url = $8, linked_version_id = $9, updated_at = now()
WHERE id = $1
RETURNING id, product_id, status, collection_method, source_platform, source_url, content_type, content_text, content_image_url, author_name, author_title, author_avatar_url, proof_date, linked_version_id, is_featured, display_order, created_at, updated_at
`

type UpdateProofParams struct {
	ID              uuid.UUID      `json:"id"`
	ContentText     pgtype.Text    `json:"content_text"`
	ContentImageUrl pgtype.Text    `json:"content_image_url"`
	AuthorName      string         `json:"author_name"`
	AuthorTitle     pgtype.Text    `json:"author_title"`
	AuthorAvatarUrl pgtype.Text    `json:"author_avatar_url"`
	SourcePlatform  SourcePlatform `json:"source_platform"`
	SourceUrl       pgtype.Text    `json:"source_url"`
	LinkedVersionID pgtype.UUID    `json:"linked_version_id"`
}

func (q *Queries) UpdateProof(ctx context.Context, arg UpdateProofParams) (Proof, error) {
	row := q.db.QueryRow(ctx, updateProof,
		arg.ID,
		arg.ContentText,
		arg.ContentImageUrl,
		arg.AuthorName,
		arg.AuthorTitle,
		arg.AuthorAvatarUrl,
		arg.SourcePlatform,
		arg.SourceUrl,
		arg.LinkedVersionID,
	)
	var i Proof
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Status,
		&i.CollectionMethod,
		&i.SourcePlatform,
		&i.SourceUrl,
		&i.ContentType,
		&i.ContentText,
		&i.ContentImageUrl,
		&i.AuthorName,
		&i.AuthorTitle,
		&i.AuthorAvatarUrl,
		&i.ProofDate,
		&i.LinkedVersionID,
		&i.IsFeatured,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProofOrder = `-- name: UpdateProofOrder :exec
UPDATE proofs SET display_order = $2, updated_at = now()
WHERE id = $1
`

type UpdateProofOrderParams struct {
	ID           uuid.UUID `json:"id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) UpdateProofOrder(ctx context.Context, arg UpdateProofOrderParams) error {
	_, err := q.db.Exec(ctx, updateProofOrder, arg.ID, arg.DisplayOrder)
	return err
}
