// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddProofToEmbed(ctx context.Context, arg AddProofToEmbedParams) (EmbedProof, error)
	AddProofToProofPage(ctx context.Context, arg AddProofToProofPageParams) error
	AddProofToSpace(ctx context.Context, arg AddProofToSpaceParams) (SpaceProof, error)
	AddProofToWall(ctx context.Context, arg AddProofToWallParams) (WallProof, error)
	AddTagToProof(ctx context.Context, arg AddTagToProofParams) (ProofTag, error)
	ApproveProof(ctx context.Context, id uuid.UUID) (Proof, error)
	CheckProofPageSlugAvailable(ctx context.Context, arg CheckProofPageSlugAvailableParams) (int64, error)
	CountDraftsThisMonth(ctx context.Context, userID uuid.UUID) (int64, error)
	CountEmbedsByProductID(ctx context.Context, productID uuid.UUID) (int64, error)
	CountPendingProofsByProduct(ctx context.Context, productID uuid.UUID) (int64, error)
	CountProductsByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CountProofsByProductID(ctx context.Context, productID uuid.UUID) (int64, error)
	CountSpacesByProductID(ctx context.Context, productID uuid.UUID) (int64, error)
	CountUsersAdmin(ctx context.Context, search string) (int32, error)
	CountVersionsByProductID(ctx context.Context, productID uuid.UUID) (int64, error)
	CountViewsByEntity(ctx context.Context, arg CountViewsByEntityParams) (int64, error)
	CountViewsByProduct(ctx context.Context, productID uuid.UUID) ([]CountViewsByProductRow, error)
	CountViewsByProductGrouped(ctx context.Context, productID uuid.UUID) ([]CountViewsByProductGroupedRow, error)
	CountWallsByProductID(ctx context.Context, productID uuid.UUID) (int64, error)
	CreateDefaultWidgetConfig(ctx context.Context, productID uuid.UUID) (WidgetConfig, error)
	CreateEmbed(ctx context.Context, arg CreateEmbedParams) (Embed, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProof(ctx context.Context, arg CreateProofParams) (Proof, error)
	CreatePublicProof(ctx context.Context, arg CreatePublicProofParams) (Proof, error)
	CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVersion(ctx context.Context, arg CreateVersionParams) (LaunchVersion, error)
	CreateWall(ctx context.Context, arg CreateWallParams) (Wall, error)
	DeleteDraftByProductID(ctx context.Context, productID uuid.UUID) error
	DeleteEmbed(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProof(ctx context.Context, id uuid.UUID) error
	DeleteSpace(ctx context.Context, id uuid.UUID) error
	DeleteVersion(ctx context.Context, id uuid.UUID) error
	DeleteWall(ctx context.Context, id uuid.UUID) error
	GetDraftByProductID(ctx context.Context, productID uuid.UUID) (LaunchDraft, error)
	GetEmbedByID(ctx context.Context, id uuid.UUID) (Embed, error)
	GetEmbedBySlug(ctx context.Context, slug string) (Embed, error)
	GetMaxVersionNumber(ctx context.Context, productID uuid.UUID) (int32, error)
	GetPageViewsByDay(ctx context.Context, period pgtype.Interval) ([]GetPageViewsByDayRow, error)
	GetPeriodPageViews(ctx context.Context, period pgtype.Interval) (int32, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductByProofPageSlug(ctx context.Context, proofPageSlug string) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProofByID(ctx context.Context, id uuid.UUID) (Proof, error)
	GetProofPageConfig(ctx context.Context, id uuid.UUID) (GetProofPageConfigRow, error)
	GetPublicProofPageData(ctx context.Context, proofPageSlug string) (GetPublicProofPageDataRow, error)
	GetRecentSignups(ctx context.Context) ([]GetRecentSignupsRow, error)
	GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error)
	GetSpaceBySlug(ctx context.Context, slug string) (Space, error)
	GetTodayPageViews(ctx context.Context) (int32, error)
	GetTopPages(ctx context.Context, period pgtype.Interval) ([]GetTopPagesRow, error)
	GetTopReferrers(ctx context.Context, period pgtype.Interval) ([]GetTopReferrersRow, error)
	GetTopUTMSources(ctx context.Context, period pgtype.Interval) ([]GetTopUTMSourcesRow, error)
	GetTotalPageViews(ctx context.Context) (int32, error)
	GetTotalProducts(ctx context.Context) (int32, error)
	GetTotalProofs(ctx context.Context) (int32, error)
	GetUTMCampaigns(ctx context.Context, period pgtype.Interval) ([]GetUTMCampaignsRow, error)
	GetUserByApiKey(ctx context.Context, apiKey pgtype.Text) (User, error)
	GetUserByClerkID(ctx context.Context, clerkID string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID pgtype.Text) (User, error)
	GetUserStats(ctx context.Context) (GetUserStatsRow, error)
	GetVersionByID(ctx context.Context, id uuid.UUID) (LaunchVersion, error)
	GetWallByID(ctx context.Context, id uuid.UUID) (Wall, error)
	GetWallBySlug(ctx context.Context, slug string) (Wall, error)
	GetWidgetConfigByProductID(ctx context.Context, productID uuid.UUID) (WidgetConfig, error)
	IsUserAdmin(ctx context.Context, clerkID string) (bool, error)
	ListApprovedProofsByProductID(ctx context.Context, productID uuid.UUID) ([]Proof, error)
	ListDistinctTagsByProductID(ctx context.Context, productID uuid.UUID) ([]string, error)
	ListEmbedsByProductID(ctx context.Context, productID uuid.UUID) ([]Embed, error)
	ListProductsByUserID(ctx context.Context, userID uuid.UUID) ([]Product, error)
	ListProofPageProofs(ctx context.Context, productID uuid.UUID) ([]ListProofPageProofsRow, error)
	ListProofsByEmbedID(ctx context.Context, embedID uuid.UUID) ([]ListProofsByEmbedIDRow, error)
	ListProofsByProductID(ctx context.Context, productID uuid.UUID) ([]Proof, error)
	ListProofsBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]ListProofsBySpaceIDRow, error)
	ListProofsByWallID(ctx context.Context, wallID uuid.UUID) ([]ListProofsByWallIDRow, error)
	ListPublicProofPageProofs(ctx context.Context, productID uuid.UUID) ([]Proof, error)
	ListSpacesByProductID(ctx context.Context, productID uuid.UUID) ([]Space, error)
	ListTagsByProofID(ctx context.Context, proofID uuid.UUID) ([]ProofTag, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error)
	ListVersionsByProductID(ctx context.Context, productID uuid.UUID) ([]ListVersionsByProductIDRow, error)
	ListWallsByProductID(ctx context.Context, productID uuid.UUID) ([]Wall, error)
	MarkTrialUsed(ctx context.Context, arg MarkTrialUsedParams) error
	RecordPageView(ctx context.Context, arg RecordPageViewParams) error
	RecordView(ctx context.Context, arg RecordViewParams) error
	RejectProof(ctx context.Context, id uuid.UUID) (Proof, error)
	RemoveProofFromEmbed(ctx context.Context, arg RemoveProofFromEmbedParams) error
	RemoveProofFromProofPage(ctx context.Context, arg RemoveProofFromProofPageParams) error
	RemoveProofFromSpace(ctx context.Context, arg RemoveProofFromSpaceParams) error
	RemoveProofFromWall(ctx context.Context, arg RemoveProofFromWallParams) error
	RemoveTagFromProof(ctx context.Context, arg RemoveTagFromProofParams) error
	SetUserApiKey(ctx context.Context, arg SetUserApiKeyParams) (User, error)
	ToggleProofFeatured(ctx context.Context, id uuid.UUID) (Proof, error)
	UpdateDraftContent(ctx context.Context, arg UpdateDraftContentParams) (LaunchDraft, error)
	UpdateEmbed(ctx context.Context, arg UpdateEmbedParams) (Embed, error)
	UpdateEmbedConfig(ctx context.Context, arg UpdateEmbedConfigParams) (Embed, error)
	UpdateEmbedProofOrder(ctx context.Context, arg UpdateEmbedProofOrderParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProof(ctx context.Context, arg UpdateProofParams) (Proof, error)
	UpdateProofExtractedContent(ctx context.Context, arg UpdateProofExtractedContentParams) error
	UpdateProofOrder(ctx context.Context, arg UpdateProofOrderParams) error
	UpdateProofPageConfig(ctx context.Context, arg UpdateProofPageConfigParams) error
	UpdateProofPageProofOrder(ctx context.Context, arg UpdateProofPageProofOrderParams) error
	UpdateProofPageSlug(ctx context.Context, arg UpdateProofPageSlugParams) error
	UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error)
	UpdateSpaceConfig(ctx context.Context, arg UpdateSpaceConfigParams) (Space, error)
	UpdateSpaceProofOrder(ctx context.Context, arg UpdateSpaceProofOrderParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) (User, error)
	UpdateWall(ctx context.Context, arg UpdateWallParams) (Wall, error)
	UpdateWallConfig(ctx context.Context, arg UpdateWallConfigParams) (Wall, error)
	UpdateWallProofOrder(ctx context.Context, arg UpdateWallProofOrderParams) error
	UpdateWidgetConfig(ctx context.Context, arg UpdateWidgetConfigParams) (WidgetConfig, error)
	UpsertDraft(ctx context.Context, arg UpsertDraftParams) (LaunchDraft, error)
	UpsertUserByClerkID(ctx context.Context, arg UpsertUserByClerkIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
