// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countSpacesByProductID = `-- name: CountSpacesByProductID :one
SELECT COUNT(*) FROM spaces WHERE product_id = $1
`

func (q *Queries) CountSpacesByProductID(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSpacesByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (product_id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, product_id, name, slug, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at
`

type CreateSpaceParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace, arg.ProductID, arg.Name, arg.Slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.MaxItems,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, product_id, name, slug, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at FROM spaces WHERE id = $1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.MaxItems,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpaceBySlug = `-- name: GetSpaceBySlug :one
SELECT id, product_id, name, slug, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at FROM spaces WHERE slug = $1
`

func (q *Queries) GetSpaceBySlug(ctx context.Context, slug string) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceBySlug, slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.MaxItems,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpacesByProductID = `-- name: ListSpacesByProductID :many
SELECT id, product_id, name, slug, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at FROM spaces WHERE product_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSpacesByProductID(ctx context.Context, productID uuid.UUID) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.Theme,
			&i.MaxItems,
			&i.ShowPlatformIcon,
			&i.BorderRadius,
			&i.CardSpacing,
			&i.ShowBranding,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, slug, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at
`

type UpdateSpaceParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpace, arg.ID, arg.Name)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.MaxItems,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSpaceConfig = `-- name: UpdateSpaceConfig :one
UPDATE spaces SET
    theme = $2,
    max_items = $3,
    show_platform_icon = $4,
    border_radius = $5,
    card_spacing = $6,
    show_branding = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, slug, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at
`

type UpdateSpaceConfigParams struct {
	ID               uuid.UUID   `json:"id"`
	Theme            WidgetTheme `json:"theme"`
	MaxItems         int32       `json:"max_items"`
	ShowPlatformIcon bool        `json:"show_platform_icon"`
	BorderRadius     int32       `json:"border_radius"`
	CardSpacing      int32       `json:"card_spacing"`
	ShowBranding     bool        `json:"show_branding"`
}

func (q *Queries) UpdateSpaceConfig(ctx context.Context, arg UpdateSpaceConfigParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpaceConfig,
		arg.ID,
		arg.Theme,
		arg.MaxItems,
		arg.ShowPlatformIcon,
		arg.BorderRadius,
		arg.CardSpacing,
		arg.ShowBranding,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.MaxItems,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
