// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countSpacesByProductID = `-- name: CountSpacesByProductID :one
SELECT COUNT(*) FROM spaces WHERE product_id = $1
`

func (q *Queries) CountSpacesByProductID(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSpacesByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (product_id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, product_id, name, slug, theme, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_color, bg_opacity, layout, rows
`

type CreateSpaceParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace, arg.ProductID, arg.Name, arg.Slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgColor,
		&i.BgOpacity,
		&i.Layout,
		&i.Rows,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, product_id, name, slug, theme, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_color, bg_opacity, layout, rows FROM spaces WHERE id = $1
`

func (q *Queries) GetSpaceByID(ctx context.Context, id uuid.UUID) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceByID, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgColor,
		&i.BgOpacity,
		&i.Layout,
		&i.Rows,
	)
	return i, err
}

const getSpaceBySlug = `-- name: GetSpaceBySlug :one
SELECT id, product_id, name, slug, theme, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_color, bg_opacity, layout, rows FROM spaces WHERE slug = $1
`

func (q *Queries) GetSpaceBySlug(ctx context.Context, slug string) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceBySlug, slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgColor,
		&i.BgOpacity,
		&i.Layout,
		&i.Rows,
	)
	return i, err
}

const listSpacesByProductID = `-- name: ListSpacesByProductID :many
SELECT id, product_id, name, slug, theme, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_color, bg_opacity, layout, rows FROM spaces WHERE product_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSpacesByProductID(ctx context.Context, productID uuid.UUID) ([]Space, error) {
	rows, err := q.db.Query(ctx, listSpacesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.Theme,
			&i.ShowPlatformIcon,
			&i.BorderRadius,
			&i.CardSpacing,
			&i.ShowBranding,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VisibleCount,
			&i.CardSize,
			&i.CardHeight,
			&i.TextFontSize,
			&i.TextFont,
			&i.TextBold,
			&i.BgColor,
			&i.BgOpacity,
			&i.Layout,
			&i.Rows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, slug, theme, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_color, bg_opacity, layout, rows
`

type UpdateSpaceParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpace, arg.ID, arg.Name)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgColor,
		&i.BgOpacity,
		&i.Layout,
		&i.Rows,
	)
	return i, err
}

const updateSpaceConfig = `-- name: UpdateSpaceConfig :one
UPDATE spaces SET
    theme = $2,
    show_platform_icon = $3,
    border_radius = $4,
    card_spacing = $5,
    show_branding = $6,
    visible_count = $7,
    card_size = $8,
    card_height = $9,
    text_font_size = $10,
    text_font = $11,
    text_bold = $12,
    bg_color = $13,
    bg_opacity = $14,
    layout = $15,
    rows = $16,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, slug, theme, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, visible_count, card_size, card_height, text_font_size, text_font, text_bold, bg_color, bg_opacity, layout, rows
`

type UpdateSpaceConfigParams struct {
	ID               uuid.UUID   `json:"id"`
	Theme            WidgetTheme `json:"theme"`
	ShowPlatformIcon bool        `json:"show_platform_icon"`
	BorderRadius     int32       `json:"border_radius"`
	CardSpacing      int32       `json:"card_spacing"`
	ShowBranding     bool        `json:"show_branding"`
	VisibleCount     int32       `json:"visible_count"`
	CardSize         int32       `json:"card_size"`
	CardHeight       int32       `json:"card_height"`
	TextFontSize     int32       `json:"text_font_size"`
	TextFont         string      `json:"text_font"`
	TextBold         bool        `json:"text_bold"`
	BgColor          string      `json:"bg_color"`
	BgOpacity        int32       `json:"bg_opacity"`
	Layout           string      `json:"layout"`
	Rows             int32       `json:"rows"`
}

func (q *Queries) UpdateSpaceConfig(ctx context.Context, arg UpdateSpaceConfigParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpaceConfig,
		arg.ID,
		arg.Theme,
		arg.ShowPlatformIcon,
		arg.BorderRadius,
		arg.CardSpacing,
		arg.ShowBranding,
		arg.VisibleCount,
		arg.CardSize,
		arg.CardHeight,
		arg.TextFontSize,
		arg.TextFont,
		arg.TextBold,
		arg.BgColor,
		arg.BgOpacity,
		arg.Layout,
		arg.Rows,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.Theme,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VisibleCount,
		&i.CardSize,
		&i.CardHeight,
		&i.TextFontSize,
		&i.TextFont,
		&i.TextBold,
		&i.BgColor,
		&i.BgOpacity,
		&i.Layout,
		&i.Rows,
	)
	return i, err
}
