// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: space_proofs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProofToSpace = `-- name: AddProofToSpace :one
INSERT INTO space_proofs (space_id, proof_id, display_order)
VALUES ($1, $2, $3)
ON CONFLICT (space_id, proof_id) DO UPDATE SET display_order = EXCLUDED.display_order
RETURNING id, space_id, proof_id, display_order
`

type AddProofToSpaceParams struct {
	SpaceID      uuid.UUID `json:"space_id"`
	ProofID      uuid.UUID `json:"proof_id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) AddProofToSpace(ctx context.Context, arg AddProofToSpaceParams) (SpaceProof, error) {
	row := q.db.QueryRow(ctx, addProofToSpace, arg.SpaceID, arg.ProofID, arg.DisplayOrder)
	var i SpaceProof
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ProofID,
		&i.DisplayOrder,
	)
	return i, err
}

const listProofsBySpaceID = `-- name: ListProofsBySpaceID :many
SELECT p.id, p.product_id, p.status, p.collection_method, p.source_platform, p.source_url, p.content_type, p.content_text, p.content_image_url, p.author_name, p.author_title, p.author_avatar_url, p.proof_date, p.linked_version_id, p.is_featured, p.display_order, p.created_at, p.updated_at, p.author_email, p.author_handle, p.rating, p.video_url, p.video_duration_seconds, p.submitted_ip_hash, sp.display_order as space_display_order FROM space_proofs sp
JOIN proofs p ON p.id = sp.proof_id
WHERE sp.space_id = $1
ORDER BY sp.display_order ASC, p.created_at DESC
`

type ListProofsBySpaceIDRow struct {
	ID                   uuid.UUID        `json:"id"`
	ProductID            uuid.UUID        `json:"product_id"`
	Status               ProofStatus      `json:"status"`
	CollectionMethod     CollectionMethod `json:"collection_method"`
	SourcePlatform       SourcePlatform   `json:"source_platform"`
	SourceUrl            pgtype.Text      `json:"source_url"`
	ContentType          ContentType      `json:"content_type"`
	ContentText          pgtype.Text      `json:"content_text"`
	ContentImageUrl      pgtype.Text      `json:"content_image_url"`
	AuthorName           string           `json:"author_name"`
	AuthorTitle          pgtype.Text      `json:"author_title"`
	AuthorAvatarUrl      pgtype.Text      `json:"author_avatar_url"`
	ProofDate            pgtype.Date      `json:"proof_date"`
	LinkedVersionID      pgtype.UUID      `json:"linked_version_id"`
	IsFeatured           bool             `json:"is_featured"`
	DisplayOrder         int32            `json:"display_order"`
	CreatedAt            time.Time        `json:"created_at"`
	UpdatedAt            time.Time        `json:"updated_at"`
	AuthorEmail          pgtype.Text      `json:"author_email"`
	AuthorHandle         pgtype.Text      `json:"author_handle"`
	Rating               pgtype.Int4      `json:"rating"`
	VideoUrl             pgtype.Text      `json:"video_url"`
	VideoDurationSeconds pgtype.Int4      `json:"video_duration_seconds"`
	SubmittedIpHash      pgtype.Text      `json:"submitted_ip_hash"`
	SpaceDisplayOrder    int32            `json:"space_display_order"`
}

func (q *Queries) ListProofsBySpaceID(ctx context.Context, spaceID uuid.UUID) ([]ListProofsBySpaceIDRow, error) {
	rows, err := q.db.Query(ctx, listProofsBySpaceID, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProofsBySpaceIDRow{}
	for rows.Next() {
		var i ListProofsBySpaceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Status,
			&i.CollectionMethod,
			&i.SourcePlatform,
			&i.SourceUrl,
			&i.ContentType,
			&i.ContentText,
			&i.ContentImageUrl,
			&i.AuthorName,
			&i.AuthorTitle,
			&i.AuthorAvatarUrl,
			&i.ProofDate,
			&i.LinkedVersionID,
			&i.IsFeatured,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorEmail,
			&i.AuthorHandle,
			&i.Rating,
			&i.VideoUrl,
			&i.VideoDurationSeconds,
			&i.SubmittedIpHash,
			&i.SpaceDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProofFromSpace = `-- name: RemoveProofFromSpace :exec
DELETE FROM space_proofs WHERE space_id = $1 AND proof_id = $2
`

type RemoveProofFromSpaceParams struct {
	SpaceID uuid.UUID `json:"space_id"`
	ProofID uuid.UUID `json:"proof_id"`
}

func (q *Queries) RemoveProofFromSpace(ctx context.Context, arg RemoveProofFromSpaceParams) error {
	_, err := q.db.Exec(ctx, removeProofFromSpace, arg.SpaceID, arg.ProofID)
	return err
}

const updateSpaceProofOrder = `-- name: UpdateSpaceProofOrder :exec
UPDATE space_proofs SET display_order = $3
WHERE space_id = $1 AND proof_id = $2
`

type UpdateSpaceProofOrderParams struct {
	SpaceID      uuid.UUID `json:"space_id"`
	ProofID      uuid.UUID `json:"proof_id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) UpdateSpaceProofOrder(ctx context.Context, arg UpdateSpaceProofOrderParams) error {
	_, err := q.db.Exec(ctx, updateSpaceProofOrder, arg.SpaceID, arg.ProofID, arg.DisplayOrder)
	return err
}
