// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProductsByUserID = `-- name: CountProductsByUserID :one
SELECT COUNT(*) FROM products WHERE user_id = $1
`

func (q *Queries) CountProductsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (clerk_id, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key
`

type CreateUserParams struct {
	ClerkID   string      `json:"clerk_id"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}

const getUserByApiKey = `-- name: GetUserByApiKey :one
SELECT id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key FROM users WHERE api_key = $1
`

func (q *Queries) GetUserByApiKey(ctx context.Context, apiKey pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByApiKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key FROM users WHERE clerk_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}

const getUserByStripeCustomerID = `-- name: GetUserByStripeCustomerID :one
SELECT id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key FROM users WHERE stripe_customer_id = $1
`

func (q *Queries) GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByStripeCustomerID, stripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}

const markTrialUsed = `-- name: MarkTrialUsed :exec
UPDATE users
SET pro_trial_used = CASE WHEN $2 = 'pro' THEN true ELSE pro_trial_used END,
    business_trial_used = CASE WHEN $2 = 'business' THEN true ELSE business_trial_used END,
    updated_at = now()
WHERE id = $1
`

type MarkTrialUsedParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) MarkTrialUsed(ctx context.Context, arg MarkTrialUsedParams) error {
	_, err := q.db.Exec(ctx, markTrialUsed, arg.ID, arg.Column2)
	return err
}

const setUserApiKey = `-- name: SetUserApiKey :one
UPDATE users SET api_key = $2, updated_at = now() WHERE id = $1 RETURNING id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key
`

type SetUserApiKeyParams struct {
	ID     uuid.UUID   `json:"id"`
	ApiKey pgtype.Text `json:"api_key"`
}

func (q *Queries) SetUserApiKey(ctx context.Context, arg SetUserApiKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserApiKey, arg.ID, arg.ApiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, name = $3, avatar_url = $4, updated_at = now()
WHERE clerk_id = $1
RETURNING id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key
`

type UpdateUserParams struct {
	ClerkID   string      `json:"clerk_id"`
	Email     string      `json:"email"`
	Name      string      `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ClerkID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}

const updateUserPlan = `-- name: UpdateUserPlan :one
UPDATE users
SET plan = $2, stripe_customer_id = $3, stripe_subscription_id = $4, updated_at = now()
WHERE id = $1
RETURNING id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key
`

type UpdateUserPlanParams struct {
	ID                   uuid.UUID   `json:"id"`
	Plan                 UserPlan    `json:"plan"`
	StripeCustomerID     pgtype.Text `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text `json:"stripe_subscription_id"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPlan,
		arg.ID,
		arg.Plan,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}

const upsertUserByClerkID = `-- name: UpsertUserByClerkID :one
INSERT INTO users (clerk_id, email, name)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_id) DO UPDATE
SET email = EXCLUDED.email, name = EXCLUDED.name, updated_at = now()
RETURNING id, clerk_id, email, name, avatar_url, plan, stripe_customer_id, stripe_subscription_id, created_at, updated_at, pro_trial_used, business_trial_used, is_admin, api_key
`

type UpsertUserByClerkIDParams struct {
	ClerkID string `json:"clerk_id"`
	Email   string `json:"email"`
	Name    string `json:"name"`
}

func (q *Queries) UpsertUserByClerkID(ctx context.Context, arg UpsertUserByClerkIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByClerkID, arg.ClerkID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProTrialUsed,
		&i.BusinessTrialUsed,
		&i.IsAdmin,
		&i.ApiKey,
	)
	return i, err
}
