// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: view_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countViewsByEntity = `-- name: CountViewsByEntity :one
SELECT COUNT(*) AS view_count
FROM view_events
WHERE entity_type = $1 AND entity_id = $2
`

type CountViewsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) CountViewsByEntity(ctx context.Context, arg CountViewsByEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countViewsByEntity, arg.EntityType, arg.EntityID)
	var view_count int64
	err := row.Scan(&view_count)
	return view_count, err
}

const countViewsByProduct = `-- name: CountViewsByProduct :many
SELECT entity_type, COUNT(*) AS view_count
FROM view_events
WHERE product_id = $1
GROUP BY entity_type
`

type CountViewsByProductRow struct {
	EntityType string `json:"entity_type"`
	ViewCount  int64  `json:"view_count"`
}

func (q *Queries) CountViewsByProduct(ctx context.Context, productID uuid.UUID) ([]CountViewsByProductRow, error) {
	rows, err := q.db.Query(ctx, countViewsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountViewsByProductRow{}
	for rows.Next() {
		var i CountViewsByProductRow
		if err := rows.Scan(&i.EntityType, &i.ViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countViewsByProductGrouped = `-- name: CountViewsByProductGrouped :many
SELECT entity_type, entity_id, COUNT(*) AS view_count
FROM view_events
WHERE product_id = $1
GROUP BY entity_type, entity_id
`

type CountViewsByProductGroupedRow struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	ViewCount  int64     `json:"view_count"`
}

func (q *Queries) CountViewsByProductGrouped(ctx context.Context, productID uuid.UUID) ([]CountViewsByProductGroupedRow, error) {
	rows, err := q.db.Query(ctx, countViewsByProductGrouped, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountViewsByProductGroupedRow{}
	for rows.Next() {
		var i CountViewsByProductGroupedRow
		if err := rows.Scan(&i.EntityType, &i.EntityID, &i.ViewCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordView = `-- name: RecordView :exec
INSERT INTO view_events (entity_type, entity_id, product_id, referrer)
VALUES ($1, $2, $3, $4)
`

type RecordViewParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   uuid.UUID   `json:"entity_id"`
	ProductID  uuid.UUID   `json:"product_id"`
	Referrer   pgtype.Text `json:"referrer"`
}

func (q *Queries) RecordView(ctx context.Context, arg RecordViewParams) error {
	_, err := q.db.Exec(ctx, recordView,
		arg.EntityType,
		arg.EntityID,
		arg.ProductID,
		arg.Referrer,
	)
	return err
}
