// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wall_proofs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProofToWall = `-- name: AddProofToWall :one
INSERT INTO wall_proofs (wall_id, proof_id, display_order)
VALUES ($1, $2, $3)
ON CONFLICT (wall_id, proof_id) DO NOTHING
RETURNING id, wall_id, proof_id, display_order
`

type AddProofToWallParams struct {
	WallID       uuid.UUID `json:"wall_id"`
	ProofID      uuid.UUID `json:"proof_id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) AddProofToWall(ctx context.Context, arg AddProofToWallParams) (WallProof, error) {
	row := q.db.QueryRow(ctx, addProofToWall, arg.WallID, arg.ProofID, arg.DisplayOrder)
	var i WallProof
	err := row.Scan(
		&i.ID,
		&i.WallID,
		&i.ProofID,
		&i.DisplayOrder,
	)
	return i, err
}

const listProofsByWallID = `-- name: ListProofsByWallID :many
SELECT p.id, p.product_id, p.status, p.collection_method, p.source_platform, p.source_url, p.content_type, p.content_text, p.content_image_url, p.author_name, p.author_title, p.author_avatar_url, p.proof_date, p.linked_version_id, p.is_featured, p.display_order, p.created_at, p.updated_at, wp.display_order as wall_display_order FROM wall_proofs wp
JOIN proofs p ON p.id = wp.proof_id
WHERE wp.wall_id = $1
ORDER BY wp.display_order ASC, p.created_at DESC
`

type ListProofsByWallIDRow struct {
	ID               uuid.UUID        `json:"id"`
	ProductID        uuid.UUID        `json:"product_id"`
	Status           ProofStatus      `json:"status"`
	CollectionMethod CollectionMethod `json:"collection_method"`
	SourcePlatform   SourcePlatform   `json:"source_platform"`
	SourceUrl        pgtype.Text      `json:"source_url"`
	ContentType      ContentType      `json:"content_type"`
	ContentText      pgtype.Text      `json:"content_text"`
	ContentImageUrl  pgtype.Text      `json:"content_image_url"`
	AuthorName       string           `json:"author_name"`
	AuthorTitle      pgtype.Text      `json:"author_title"`
	AuthorAvatarUrl  pgtype.Text      `json:"author_avatar_url"`
	ProofDate        pgtype.Date      `json:"proof_date"`
	LinkedVersionID  pgtype.UUID      `json:"linked_version_id"`
	IsFeatured       bool             `json:"is_featured"`
	DisplayOrder     int32            `json:"display_order"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
	WallDisplayOrder int32            `json:"wall_display_order"`
}

func (q *Queries) ListProofsByWallID(ctx context.Context, wallID uuid.UUID) ([]ListProofsByWallIDRow, error) {
	rows, err := q.db.Query(ctx, listProofsByWallID, wallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProofsByWallIDRow{}
	for rows.Next() {
		var i ListProofsByWallIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Status,
			&i.CollectionMethod,
			&i.SourcePlatform,
			&i.SourceUrl,
			&i.ContentType,
			&i.ContentText,
			&i.ContentImageUrl,
			&i.AuthorName,
			&i.AuthorTitle,
			&i.AuthorAvatarUrl,
			&i.ProofDate,
			&i.LinkedVersionID,
			&i.IsFeatured,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WallDisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProofFromWall = `-- name: RemoveProofFromWall :exec
DELETE FROM wall_proofs WHERE wall_id = $1 AND proof_id = $2
`

type RemoveProofFromWallParams struct {
	WallID  uuid.UUID `json:"wall_id"`
	ProofID uuid.UUID `json:"proof_id"`
}

func (q *Queries) RemoveProofFromWall(ctx context.Context, arg RemoveProofFromWallParams) error {
	_, err := q.db.Exec(ctx, removeProofFromWall, arg.WallID, arg.ProofID)
	return err
}

const updateWallProofOrder = `-- name: UpdateWallProofOrder :exec
UPDATE wall_proofs SET display_order = $3
WHERE wall_id = $1 AND proof_id = $2
`

type UpdateWallProofOrderParams struct {
	WallID       uuid.UUID `json:"wall_id"`
	ProofID      uuid.UUID `json:"proof_id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) UpdateWallProofOrder(ctx context.Context, arg UpdateWallProofOrderParams) error {
	_, err := q.db.Exec(ctx, updateWallProofOrder, arg.WallID, arg.ProofID, arg.DisplayOrder)
	return err
}
