// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: walls.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countWallsByProductID = `-- name: CountWallsByProductID :one
SELECT COUNT(*) FROM walls WHERE product_id = $1
`

func (q *Queries) CountWallsByProductID(ctx context.Context, productID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWallsByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWall = `-- name: CreateWall :one
INSERT INTO walls (product_id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, product_id, name, slug, created_at, updated_at, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, header_text_color, subtitle, show_header, layout
`

type CreateWallParams struct {
	ProductID uuid.UUID `json:"product_id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
}

func (q *Queries) CreateWall(ctx context.Context, arg CreateWallParams) (Wall, error) {
	row := q.db.QueryRow(ctx, createWall, arg.ProductID, arg.Name, arg.Slug)
	var i Wall
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.ShowHeader,
		&i.Layout,
	)
	return i, err
}

const deleteWall = `-- name: DeleteWall :exec
DELETE FROM walls WHERE id = $1
`

func (q *Queries) DeleteWall(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWall, id)
	return err
}

const getWallByID = `-- name: GetWallByID :one
SELECT id, product_id, name, slug, created_at, updated_at, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, header_text_color, subtitle, show_header, layout FROM walls WHERE id = $1
`

func (q *Queries) GetWallByID(ctx context.Context, id uuid.UUID) (Wall, error) {
	row := q.db.QueryRow(ctx, getWallByID, id)
	var i Wall
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.ShowHeader,
		&i.Layout,
	)
	return i, err
}

const getWallBySlug = `-- name: GetWallBySlug :one
SELECT id, product_id, name, slug, created_at, updated_at, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, header_text_color, subtitle, show_header, layout FROM walls WHERE slug = $1
`

func (q *Queries) GetWallBySlug(ctx context.Context, slug string) (Wall, error) {
	row := q.db.QueryRow(ctx, getWallBySlug, slug)
	var i Wall
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.ShowHeader,
		&i.Layout,
	)
	return i, err
}

const listWallsByProductID = `-- name: ListWallsByProductID :many
SELECT id, product_id, name, slug, created_at, updated_at, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, header_text_color, subtitle, show_header, layout FROM walls WHERE product_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWallsByProductID(ctx context.Context, productID uuid.UUID) ([]Wall, error) {
	rows, err := q.db.Query(ctx, listWallsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wall{}
	for rows.Next() {
		var i Wall
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Theme,
			&i.BorderRadius,
			&i.CardSpacing,
			&i.ShowPlatformIcon,
			&i.ShowBranding,
			&i.BgColor,
			&i.TransparentBg,
			&i.HeaderTextColor,
			&i.Subtitle,
			&i.ShowHeader,
			&i.Layout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWall = `-- name: UpdateWall :one
UPDATE walls SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, slug, created_at, updated_at, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, header_text_color, subtitle, show_header, layout
`

type UpdateWallParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateWall(ctx context.Context, arg UpdateWallParams) (Wall, error) {
	row := q.db.QueryRow(ctx, updateWall, arg.ID, arg.Name)
	var i Wall
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.ShowHeader,
		&i.Layout,
	)
	return i, err
}

const updateWallConfig = `-- name: UpdateWallConfig :one
UPDATE walls SET
    theme = $2,
    border_radius = $3,
    card_spacing = $4,
    show_platform_icon = $5,
    show_branding = $6,
    bg_color = $7,
    transparent_bg = $8,
    header_text_color = $9,
    subtitle = $10,
    show_header = $11,
    layout = $12,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, slug, created_at, updated_at, theme, border_radius, card_spacing, show_platform_icon, show_branding, bg_color, transparent_bg, header_text_color, subtitle, show_header, layout
`

type UpdateWallConfigParams struct {
	ID               uuid.UUID   `json:"id"`
	Theme            WidgetTheme `json:"theme"`
	BorderRadius     int32       `json:"border_radius"`
	CardSpacing      int32       `json:"card_spacing"`
	ShowPlatformIcon bool        `json:"show_platform_icon"`
	ShowBranding     bool        `json:"show_branding"`
	BgColor          string      `json:"bg_color"`
	TransparentBg    bool        `json:"transparent_bg"`
	HeaderTextColor  string      `json:"header_text_color"`
	Subtitle         string      `json:"subtitle"`
	ShowHeader       bool        `json:"show_header"`
	Layout           string      `json:"layout"`
}

func (q *Queries) UpdateWallConfig(ctx context.Context, arg UpdateWallConfigParams) (Wall, error) {
	row := q.db.QueryRow(ctx, updateWallConfig,
		arg.ID,
		arg.Theme,
		arg.BorderRadius,
		arg.CardSpacing,
		arg.ShowPlatformIcon,
		arg.ShowBranding,
		arg.BgColor,
		arg.TransparentBg,
		arg.HeaderTextColor,
		arg.Subtitle,
		arg.ShowHeader,
		arg.Layout,
	)
	var i Wall
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Theme,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowPlatformIcon,
		&i.ShowBranding,
		&i.BgColor,
		&i.TransparentBg,
		&i.HeaderTextColor,
		&i.Subtitle,
		&i.ShowHeader,
		&i.Layout,
	)
	return i, err
}
