// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: widget_configs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDefaultWidgetConfig = `-- name: CreateDefaultWidgetConfig :one
INSERT INTO widget_configs (product_id)
VALUES ($1)
RETURNING id, product_id, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, layout
`

func (q *Queries) CreateDefaultWidgetConfig(ctx context.Context, productID uuid.UUID) (WidgetConfig, error) {
	row := q.db.QueryRow(ctx, createDefaultWidgetConfig, productID)
	var i WidgetConfig
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Theme,
		&i.MaxItems,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Layout,
	)
	return i, err
}

const getWidgetConfigByProductID = `-- name: GetWidgetConfigByProductID :one
SELECT id, product_id, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, layout FROM widget_configs WHERE product_id = $1
`

func (q *Queries) GetWidgetConfigByProductID(ctx context.Context, productID uuid.UUID) (WidgetConfig, error) {
	row := q.db.QueryRow(ctx, getWidgetConfigByProductID, productID)
	var i WidgetConfig
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Theme,
		&i.MaxItems,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Layout,
	)
	return i, err
}

const updateWidgetConfig = `-- name: UpdateWidgetConfig :one
UPDATE widget_configs
SET theme = $2, max_items = $3, show_platform_icon = $4, border_radius = $5, card_spacing = $6, show_branding = $7, layout = $8, updated_at = now()
WHERE product_id = $1
RETURNING id, product_id, theme, max_items, show_platform_icon, border_radius, card_spacing, show_branding, created_at, updated_at, layout
`

type UpdateWidgetConfigParams struct {
	ProductID        uuid.UUID   `json:"product_id"`
	Theme            WidgetTheme `json:"theme"`
	MaxItems         int32       `json:"max_items"`
	ShowPlatformIcon bool        `json:"show_platform_icon"`
	BorderRadius     int32       `json:"border_radius"`
	CardSpacing      int32       `json:"card_spacing"`
	ShowBranding     bool        `json:"show_branding"`
	Layout           string      `json:"layout"`
}

func (q *Queries) UpdateWidgetConfig(ctx context.Context, arg UpdateWidgetConfigParams) (WidgetConfig, error) {
	row := q.db.QueryRow(ctx, updateWidgetConfig,
		arg.ProductID,
		arg.Theme,
		arg.MaxItems,
		arg.ShowPlatformIcon,
		arg.BorderRadius,
		arg.CardSpacing,
		arg.ShowBranding,
		arg.Layout,
	)
	var i WidgetConfig
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Theme,
		&i.MaxItems,
		&i.ShowPlatformIcon,
		&i.BorderRadius,
		&i.CardSpacing,
		&i.ShowBranding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Layout,
	)
	return i, err
}
